ci/conda/recipes/cudf/build.sh, ci/conda/recipes/libcudf/build.sh, ci/conda/recipes/morpheus/morpheus_build.sh, ci/conda/recipes/run_conda_build.sh, docker/build_conda_packages.sh, docker/build_container.sh, docker/build_container_release.sh, docker/run_container_dev.sh
With a fresh build, errors occur which show the following:
```
Check for working C compiler: $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc - broken
...
ccache: error: Failed to write to /workspace/.cache/ccache/ccache.log: No such file or directory
```
This PR fixes that by ensuring the cache directories exist
Closes #7
=> Fix Docker Build by Ensuring Cache Directories Exist

data/bert-base-cased-vocab.txt, examples/log_parsing/README.md, examples/log_parsing/run.py
~- Add missing vocabulary file (`bert-base-cased-vocab.txt`)~
- Fix path to run script in example README
- Use `os.cpu_count()` instead of `psutil.cpu_count()` for pipeline config's `num_threads`
=> Log parsing example updates

ci/conda/recipes/morpheus/meta.yaml
Conda build was missing `pytest-benchmark`
=> Fixing pytest in conda build

docker/build_container_release.sh, docker/run_container_release.sh, docs/source/index.rst
Updates the buid/run docker release scripts to use the new format.
=> Changing runtime-22.04 to 22.04-runtime

ci/conda/recipes/run_conda_build.sh, docker/Dockerfile
If there are 404 errors for the channels `nvidia` or `rapidsai`, then the conda-build scripts can fail. This adds the option to specify `CONDA_CHANNEL_ALIAS` before calling `./ci/conda/recipes/run_conda_build.sh`.
Since we are currently getting these errors, the option has been enabled by default in the docker container builds but will not be used unless manually specified.
=> Adding option to specify a conda channel alias during conda-build

ci/conda/recipes/run_conda_build.sh, docker/Dockerfile
To use a conda channel alias/mirror, use the following:
```
DOCKER_EXTRA_ARGS="--build-arg CONDA_CHANNEL_ALIAS=<alias_url>" ./build_container_release.sh
```
=> Adding build arg to use conda mirror

examples/nlp_si_detection/README.md
I was getting a failed assert with the original pipeline, I added `--truncation=True` to the pre-process stage which caused the assert to go away, can someone confirm this is correct?
```
Check failed: this->mess_count == this->count At this time, mess_count and count must be the same for slicing
```
* Update version fo triton
* Remove ref to git submodule
* Fix path to labels file
* Remove buffer stages
* Remove vizualization flag
* Add `--truncation=True` to the preprocess stage
* Morpheus stops on its own now
fixes #59
=> Fix the nlp_si_detection example

tests/conftest.py
Fixes an issue where during the run of pytest `configure_logging` was being called multiple times resulting in several duplicate log handlers being added to the morpheus logger.
Fixes #63
=> Clear log handlers after each test

docker/Dockerfile
Developers will need to execute 
```bash
docker pull docker.io/gpuci/miniforge-cuda:11.4-devel-ubuntu20.04
```
To ensure their base image is up to date.
This reverts commit f1de88fa3f65b1d179c3402496952b48edf7b4de.
=> Revert "Install new apt key"

README.md
Updated the `README.md` file as below.
- Removed reference to getting started on NGC (was causing confusion)
- Reworked language on getting started on GitHub
- Minor formatting issues in the Kafka quick start section
=> Updates to README.md for clarity

scripts/get-triton-config.sh
Utility script to render a "starter" Triton config from onnx, tf or trt "bare" models.
Mix of bash, jq, sed, and awk. Over time could be replaced by python with proper json and protobuf libraries. Best effort attempt to preserve gpu, cpu accelerator and optional parameters fields if the model in fact has its own config.pbtxt. 
From the help:
```
This script retrieves a computed model configuration from NVIDIA Triton. The Triton
Inference Server can be launched with "--strict-model-config=false" which means it
will create a minimal Triton configuration (config.pbtxt) from the required
elements of a model if one has not been provided.
This only applies to TensorRT, TensorFlow saved-model, and ONNX models. Once the
initial configuration file is derived, it is expected that optional and …
```
=> Add script to capture triton config

morpheus/CMakeLists.txt
To cover situations where the version of the Python interpreter provided by the OS is newer than the one in the Conda env.
Fixes #75
=> Set Python3_FIND_STRATEGY=Location

ci/Jenkinsfile, ci/scripts/jenkins/common.sh
+ Use Github's rest API to determine base branch.
+ Only run check stage on pull requests
=> Fix for CI check script

ci/conda/recipes/morpheus/meta.yaml
The docker release build fails because `pybind11-stubgen` is missing from the conda-build requirements.
Fixes #140
=> Adding in pybind11-stubgen to the conda package

docker/Dockerfile
Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
=> [gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

CMakeLists.txt, ci/Jenkinsfile
Rolls back the ci images to 22.04 and removes the ci build fix necessary for those images, because the fixes are causing issues for compilations done from within the dev container.
Closes #190
=> Rollback CI images and fix dev container

examples/gnn_fraud_detection_pipeline/README.md, examples/gnn_fraud_detection_pipeline/requirements.yml, examples/gnn_fraud_detection_pipeline/stages/classification_stage.py, examples/gnn_fraud_detection_pipeline/stages/graph_construction_stage.py, examples/gnn_fraud_detection_pipeline/stages/graph_sage_stage.py
=> Fix GNN example and update installation instructions

examples/nlp_si_detection/README.md, morpheus/_lib/src/python_modules/messages.cpp
* Add a second monitor stage to report progress for the back-half of the pipeline
* Increase threads to match number of stages
* Change triton port to 8000 avoiding a warning about the grpc port
* Add EdgeConnectors for derived classes of MultiMessage to MultiMessage
* Remove filter stage from example #83 & #197
fixes #186
=> nlp_si_detection example improvements

docker/Dockerfile
Forces the docker build to use git version 2.35.3. Otherwise conda build breaks during release container builds.
Fixes #223
=> Use git version 2.35.3 in release build

morpheus/cli.py, tests/test_cli.py
In PR #130 we moved the `data` directory into `morpheus/data` and installed it with the python package. This required changing some of the default CLI arguments from relative paths like `data/labels_nlp.txt` to absolute paths like `morpheus.DATA_DIR/labels_nlp.txt`.
To make it easy for the user to see how to change the labels file, we respecified the default argument value in documentation (i.e. `--labels_file=data/labels_nlp.txt`). Now that this needs to be an absolute path, the command in the documentation does not work. Adding absolute paths in the documentation is not feasible since this would require very long paths that would change from machine to machine.
Instead, if the user specifies a data file with a relative path, we first check to see if a file exists relative to the current …
=> Add CLI Relative Path Fallback

examples/log_parsing/postprocessing.py, examples/log_parsing/preprocessing.py
Added missing abstract implementation function to `log_parsing` example preproc and postproc stages.
=> Missing 'supports_cpp_node' impl function

docker/conda/environments/cuda11.5_dev.yml, morpheus/stages/output/write_to_kafka_stage.py
Fixes #244 
The kafka stage needs to be a pass through node.
=> Fixing `to-kafka` Stage by Converting to a Pass Through Node

ci/conda/recipes/morpheus/meta.yaml, docker/conda/environments/cuda11.5_dev.yml
The release of `cuda-python=11.7.1` has broken both the builds and the CI. See PR #246 which fixed the CI. This PR fixes the conda build.
Issue #251 has been created to remove this dependency in the future.
Fixes #250
=> Pin Conda Package `cuda-python <=11.7.0` to Fix Conda Build

ci/scripts/gitutils.py, docs/source/conf.py, models/mlflow/docker/Dockerfile, models/mlflow/docker/entrypoint.sh, models/training-tuning-scripts/fraud-detection-models/HinSAGE.py, models/training-tuning-scripts/hammah-models/hammah-20211017-script.py, models/training-tuning-scripts/phishing-models/binary_sequence_classifier.py, models/training-tuning-scripts/phishing-models/phish-bert-20211006-script.py, models/training-tuning-scripts/phishing-models/sequence_classifier.py, models/validation-inference-scripts/abp-models/abp-inference.py, models/validation-inference-scripts/fraud-detection-models/inference.py, models/validation-inference-scripts/hammah-models/hammah-inference.py, models/validation-inference-scripts/hammah-models/requirements.txt, models/validation-inference-scripts/log-parsing-models/log-parsing-inference.py, models/validation-inference-scripts/phishing-models/phish-bert-20220113-inference-script.py, morpheus/_lib/include/morpheus/objects/triton_in_out.hpp, morpheus/_lib/include/nvtext/subword_tokenize.hpp, tests/mock_triton_server/config.yml
Fixes style checks preventing #237 from passing
=> Fix 22.06 style checks

CONTRIBUTING.md, morpheus/_lib/src/stages/kafka_source.cpp, morpheus/cli.py, morpheus/stages/input/kafka_source_stage.py
Fixes #254 
This re-enables the check on the number of messages received before trying to process to cudf.
=> Fixing the from-kafka stage

morpheus/stages/general/monitor_stage.py
Improves readability of the output from the monitor stage
Changes output from:
```
FromFile rate[Complete]: 93085messages [00:01, 89424.59messages/s]
```
To:
```
FromFile rate[Complete]: 93085 messages [00:01, 89424.59 messages/s]
```
All I did was just insert a blank space in front of the unit name. As far as I can tell tqdm doesn't give control over the `rate_fmt`:
https://github.com/tqdm/tqdm/blob/master/tqdm/std.py#L445
=> MonitorStage add a blank space between the rate and the unit description

CHANGELOG.md, ci/Jenkinsfile, ci/conda/recipes/morpheus/meta.yaml, ci/scripts/jenkins/build.sh, ci/scripts/jenkins/common.sh, ci/scripts/jenkins/docs.sh, docker/Dockerfile, examples/log_parsing/postprocessing.py, models/training-tuning-scripts/fraud-detection-models/requirements.txt, models/validation-inference-scripts/fraud-detection-models/requirements.txt, models/validation-inference-scripts/hammah-models/requirements.txt, models/validation-inference-scripts/phishing-models/requirements.txt
This is the PR containing all of the changes for the 22.06.01 Hotfix
=> [RELEASE] Morpheus v22.06.01 Hotfix

CONTRIBUTING.md, README.md, scripts/validation/val-globals.sh, scripts/validation/val-utils.sh
Also updates:
* Git LFS instructions
* Software requirements
* Specifics that apply to all users were moved from `CONTRIBUTING.md` to `README.md`
* Default version of Triton used by Validation scripts updated to 22.06 
Fixes #288
=> Updates README.md to include instructions for launching Triton

morpheus/_lib/cmake/libraries/cuda_utils.cmake, morpheus/_lib/cmake/libraries/morpheus.cmake, morpheus/_lib/include/morpheus/objects/table_info.hpp
* Removes `table_info.cpp` from `morpheus.cmake`
* Sets visibility on the `TableInfo.as_py_object` method, this was showing up as undefined in `libmorpheus.so`. 
I tried just setting `#pragma GCC visibility push(default)` at the top of the class definition, but this didn't work, according to the gcc docs this is intentional:
> In C++, ‘#pragma GCC visibility’ affects only namespace-scope declarations. Class members and template specializations are not affected; if you want to override the visibility for a particular member or instantiation, you must use an attribute.
https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Visibility-Pragmas.html
fixes #271
=> Ensure TableInfo only appears in one lib

ci/conda/recipes/morpheus/meta.yaml, docker/conda/environments/cuda11.5_dev.yml, docker/conda/environments/requirements.txt, setup.py
Looks like the `grpcio-channelz` package has been breaking CI. Since this package isnt even used anywhere since the `streamz` days, we should remove it.
=> Removing `grpcio-channelz`

README.md, docs/source/developer_guide/guides/2_real_world_phishing.md, examples/abp_nvsmi_detection/README.md, examples/abp_pcap_detection/README.md, examples/log_parsing/README.md, examples/nlp_si_detection/README.md, examples/ransomware_detection/README.md, examples/sid_visualization/docker-compose.yml, models/triton-model-repo/README.md, scripts/validation/kafka_testing.md, scripts/validation/val-globals.sh, scripts/validation/val-utils.sh, tests/benchmarks/README.md
General refresh of some out-of-date tritonserver image references
=> Wholesale updates for tritonserver version

cmake/dependencies.cmake, docker/conda/environments/cuda11.5_dev.yml
=> Move to srf-22.11 alpha

tests/test_config.py
This test currently only works when run after other tests which import `morpheus.config`
=> Add missing import

README.md, docs/source/morpheus_quickstart_guide.md, models/mlflow/README.md
- To make the command easier to copy and paste, the `$` symbol was removed.
- Removed duplicate table of contents
=> Update Quickstart Guide

ci/scripts/github/test.sh, docker/Dockerfile, docker/conda/environments/cuda11.5_dev.yml, docker/conda/environments/requirements.txt, tests/mock_triton_server/config.yml
v0.10 was released on 2022-10-25 and completely breaks our tests which depends on it.
pytest-benchmark 4.0 fixes an incompatibility with pytest 7.2
=> Pin camouflage to v0.9 and ensure pytest-benchmark>=4

docker/build_container.sh
On my system using `docker buildx build` gives this error:
```
$ ./docker/build_container_dev.sh 
Building morpheus:...
FROM_IMAGE      : gpuci/miniforge-cuda
CUDA_VER        : 11.5
LINUX_DISTRO    : ubuntu
LINUX_VER       : 20.04
RAPIDS_VER      : 22.04
PYTHON_VER      : 3.8
TENSORRT_VERSION: 8.2.1.3
COMMAND: docker buildx build -t morpheus:dev-221025 --target development --build-arg FROM_IMAGE=gpuci/miniforge-cuda --build-arg CUDA_VER=11.5 --build-arg LINUX_DISTRO=ubuntu --build-arg LINUX_VER=20.04 --build-arg RAPIDS_VER=22.04 --build-arg PYTHON_VER=3.8 --build-arg TENSORRT_VERSION=8.2.1.3 --network=host  -f docker/Dockerfile .
Note: add '--progress plain' to DOCKER_ARGS to show all container build output
unknown shorthand flag: 't' in -t
See 'docker --help'.
Usage:  docker [OPTIONS] …
```
=> Remove buildx from docker command causes issues with docker 20.10.5

docker/build_container.sh, morpheus/_lib/include/morpheus/objects/tensor_object.hpp, morpheus/_lib/src/messages/multi.cpp, tests/test_abp.py, tests/test_add_scores_stage_pipe.py, tests/test_filter_detections_stage_pipe.py, tests/test_sid.py, tests/utils.py
=> Properly calculate the offset of the column_view & apply offsets in copy_meta_ranges

examples/gnn_fraud_detection_pipeline/README.md, examples/gnn_fraud_detection_pipeline/requirements.yml
Fixes an issue where without specifying the `nvidia/label/dev` channel conda/mamba will install an old version of tensorflow (2.4.1) which is unable to load the model file.
fixes #324
=> Set channels and versions to ensure we get a good version of tensorflow

tests/conftest.py, tests/mock_triton_server/mocks/reset/POST.mock, tests/mock_triton_server/mocks/v2/models/abp-nvsmi-xgb/infer/POST.mock, tests/mock_triton_server/mocks/v2/models/phishing-bert-onnx/infer/POST.mock, tests/mock_triton_server/mocks/v2/models/sid-minibert-onnx-no-trunc/infer/POST.mock, tests/mock_triton_server/mocks/v2/models/sid-minibert-onnx/infer/POST.mock
If a test crashes or a developer stops a test in the middle of debugging, Camouflage will be left open. Any subsequent runs of pytest will fail to start.
This fixes the issue by binding the child process to the pytest process, ensuring that it will always be closed. Also added support for using already running Camouflage servers.
Closes #329
=> Ensure Camouflage is shutdown after every test

examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_batcher_stage.py
Fixes bug when two files have the same timestamp.
This tends to happen when receiving data from someone else via a tar file and the filenames don't contain a timestamp, causing the stage to use the filesystem's modified time.
fixes #449
=> DFPFileBatcherStage: Sort only by timestamp

tests/test_multi_segment.py
Removes code that is always bypassed and would fail anyways.
=> Remove warning about tests not having a return value

models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.ipynb
removing `to_array` to avoid this error
----> 1 y_pred = fil_preds_gpu.to_array()
2 y_true = y_test.to_array()
3 accuracy_score(y_true, y_pred)
AttributeError: 'numpy.ndarray' object has no attribute 'to_array
Closes #469
=> update for numpy array results on ABP notebook

.gitmodules, examples/sid_visualization/viz
With the addition of multiple visualizations in the morpheus-visualizations repo, we now can have multiple examples that need the submodule.
To fix this, the submodule has been moved into `external/morpheus-visualizations` and symlinks created back to the examples folder.
=> Update External Repo to Single Directory

.github/workflows/pull_request.yml
With the updated compilers and dependencies, a new CI image is needed.
=> Updating CI runner image for MRC and C++20

examples/abp_pcap_detection/README.md
* Remove `<MORPHEUS_ROOT>` making all bash commands copy/past-able 
* Remove polling flags from Triton command
=> Minor fixes/updates to abp_pcap_detection example

examples/basic_usage/README.md
* Separate commands from output
* Remove $ prompts allowing commands to be easily copy/paste-able
=> Small updates to examples/basic_usage/README.md

examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_mlflow_model_writer.py
`dfencoder` is being updated in this [PR](https://github.com/nv-morpheus/dfencoder/pull/6) to no longer store `mean` and `std` in the AutoEncoder model. This will cause an error in `DFPMLFlowModelWriterStage` where it tries to publish `mean` and `std` as metrics to MLflow. This PR updates `DFPMLFlowModelWriterStage` to no longer publish the metrics since they don't appear be used in Morpheus anymore.
=> Update DFPMLFlowModelWriterStage to no longer save mean and std metrics

.github/workflows/ci_pipe.yml, .github/workflows/pull_request.yml, ci/runner/Dockerfile, ci/runner/README.md
This is part 1 of 2 for updates needed by #618. For now, we are explicitly specifying 520 in the driver but plan on using `latest` in the future.
=> Updating the CI image to use Driver 520

morpheus/_lib/include/morpheus/io/serializers.hpp, morpheus/_lib/include/morpheus/stages/write_to_file.hpp, morpheus/_lib/src/io/serializers.cpp, morpheus/_lib/src/python_modules/stages.cpp, morpheus/_lib/src/stages/write_to_file.cpp, morpheus/_lib/tests/CMakeLists.txt, morpheus/stages/output/write_to_file_stage.py, tests/test_file_in_out_stage_pipe.py, tests/test_write_to_file_stage.py
Currently we don't flush to disk for each message. However for some sources like Kafka, there may be long periods of time between incoming messages which might be small.
* Adds new `flush` constructor argument to `WriteToFileStage`
* Ensures that we are consistent on when we flush and don't. Specifically the Python impl never flushed, but the C++ impl flushed always for json but not for csv.
fixes #558
=> WriteToFileStage optionally emit a flush on each message received

examples/digital_fingerprinting/production/morpheus/benchmarks/README.md, pyproject.toml
- Skipping DFP production directory from pytest scan
- Updated DFP benchmarks README.md with prerequisites.
=> [BUG] DFP benchmark related pytest error

examples/developer_guide/4_rabbitmq_cpp_stage/cmake/Configure_rabbitmq.cmake, examples/developer_guide/4_rabbitmq_cpp_stage/cmake/dependencies.cmake
Relates to: https://github.com/alanxz/rabbitmq-c/issues/740
fixes #678
=> Adopt v0.12.0 of rabbitmq-c and return to using a shallow checkout

morpheus/_lib/include/morpheus/utilities/tensor_util.hpp, morpheus/_lib/src/objects/dev_mem_info.cpp, morpheus/_lib/src/objects/rmm_tensor.cpp, morpheus/_lib/src/stages/triton_inference.cpp, morpheus/_lib/src/utilities/tensor_util.cpp
Simple one-liner for calculating the element count of a tensor based on the shape was copy/pasted into four different places in the code base (Likely I'm to blame for at least one of these).
This just replaces them all with a call to `TensorUtils::get_elem_count`
=> Move duplicated one-liner to TensorUtils

examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_rolling_window_stage.py
DFPRollingWindowStage was only emitting last batch once `min_history` was met. This PR updates the stage to emit all accumulated rows meeting configured window history requirements.
Fixes #674
=> Update DFPRollingWindowStage to emit correct window

morpheus.code-workspace, morpheus/cli/commands.py, morpheus/cli/register_stage.py, morpheus/cli/utils.py, morpheus/stages/input/file_source_stage.py, morpheus/stages/input/kafka_source_stage.py, morpheus/stages/output/write_to_file_stage.py, morpheus/stages/postprocess/filter_detections_stage.py, tests/test_cli.py
C++ enums exposed to Python via pybind11 are not subclasses of `enum.Enum` causing them to not be parsed properly by the CLI.
Hot-patching this into 23.01
fixes #675
=> Fix CLI parsing of C++ enum values

examples/digital_fingerprinting/production/morpheus/benchmarks/conftest.py, tests/benchmarks/conftest.py
Fixed incorrect line and byte count in  the benchmarks when using `globpath` in the configuration file.
closes #694
=> fix incorrect line and byte count benchmarks

tests/test_kafka_source_stage_pipe.py, tests/utils.py
I thought this was a bug #700 so I wrote a test, and confirmed that this wasn't actually a bug, but don't want to waste a good unittest.
=> Add unittest to ensure the kafka source is respecting the pipeline batch size

.github/workflows/label-external-issues.yml
This PR automatically adds the https://github.com/nv-morpheus/Morpheus/labels/%3F%20-%20Needs%20Triage label to all issues authored by people who have an [author_association](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation) value of that is not `OWNER` or `MEMBER`. 
The workflow is entirely skipped for org members/owners.
Right now, that means collaborators are labeled, easy to update if we want to change that.
=> [FEA]: External issue label

.gitignore, morpheus/_lib/include/morpheus/messages/memory/inference_memory.hpp, morpheus/_lib/include/morpheus/messages/memory/response_memory.hpp, morpheus/_lib/include/morpheus/messages/memory/response_memory_probs.hpp, morpheus/_lib/include/morpheus/messages/memory/tensor_memory.hpp, morpheus/_lib/include/morpheus/messages/multi.hpp, morpheus/_lib/include/morpheus/objects/rmm_tensor.hpp, morpheus/_lib/include/morpheus/objects/tensor.hpp, morpheus/_lib/include/morpheus/objects/tensor_object.hpp, morpheus/_lib/include/morpheus/types.hpp, morpheus/_lib/include/morpheus/utilities/tensor_util.hpp, morpheus/_lib/src/messages/memory/inference_memory.cpp, morpheus/_lib/src/messages/memory/inference_memory_fil.cpp, morpheus/_lib/src/messages/memory/inference_memory_nlp.cpp, morpheus/_lib/src/messages/memory/response_memory.cpp, morpheus/_lib/src/messages/memory/response_memory_probs.cpp, morpheus/_lib/src/messages/memory/tensor_memory.cpp, morpheus/_lib/src/messages/multi_tensor.cpp, morpheus/_lib/src/stages/add_classification.cpp, morpheus/_lib/src/stages/add_scores.cpp, morpheus/_lib/src/stages/preprocess_fil.cpp, morpheus/_lib/src/stages/preprocess_nlp.cpp, morpheus/_lib/src/stages/triton_inference.cpp, morpheus/_lib/src/utilities/cupy_util.cpp, morpheus/_lib/src/utilities/tensor_util.cpp, morpheus/_lib/tests/test_tensor.cpp
* Create a `types.hpp` for type aliases like `TensorIndex` and `tensor_map_t`
This is a scaled back version of PR #720 without a `forward.hpp`. The forward header didn't improve build performance, and complicated IWYU checks. The real motivation behind this was having a convenient place for `tensor_map_t`.
fixes #715
=> Create types.hpp 

.github/workflows/ci_pipe.yml, .github/workflows/pull_request.yml
This PR is using the AWS OIDC to get AWS credentials ([doc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)). Currently we are using permanent tokens that we need to manually rotate every 90 days. This PR is removing this requirement.
The `AWS_ROLE_ARN` and `AWS_REGION` are orgs variables defined here: https://github.com/organizations/nv-morpheus/settings/variables/actions.
=> Use AWS OIDC to get AWS creds

.github/workflows/ci_pipe.yml, .github/workflows/pull_request.yml
This PR is a continuation of #742.
Omitting the other keys in the `permissions` block sets them to `none` ([src](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview)).
This is probably not a concern for `nv-morpheus`, but it caused issues for some private RAPIDS repositories so I wanted to update the `nv-morpheus` repos for consistency.
To remedy this, this PR includes the following changes:
- Keeps the `id-token` permission as `write`, but sets the remaining permissions as described in the `restricted` column [here](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
- Also sets `pull_request` to `read` so that `fetch_base_branch` in `common.sh` can use it
- Moves the `permissions` block to …
=> Update workflow `permissions` block

.github/workflows/ci_pipe.yml, .github/workflows/pull_request.yml
This PR is using the AWS OIDC to get AWS credentials ([doc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)). Currently we are using permanent tokens that we need to manually rotate every 90 days. This PR is removing this requirement.
The `AWS_ROLE_ARN` and `AWS_REGION` are orgs variables defined here: https://github.com/organizations/nv-morpheus/settings/variables/actions.
Authors:
- Jordan Jacobelli (https://github.com/jjacobelli)
- David Gardner (https://github.com/dagardner-nv)
Approvers:
- AJ Schmidt (https://github.com/ajschmidt8)
- Jordan Jacobelli (https://github.com/jjacobelli)
- Michael Demoret (https://github.com/mdemoret-nv)
URL: https://github.com/nv-morpheus/Morpheus/pull/742
=> 23.01 back-patch of #742 - Use AWS OIDC to get AWS creds 

.github/workflows/label-external-issues.yml
Small PR to add `issue: write` permissions to the workflow that labels external issues.
=> [BUG] Add write permission to triage labeler action

CMakeLists.txt, morpheus/_lib/cmake/python_modules/messages.cmake, morpheus/_lib/cmake/python_modules/stages.cmake
Follow up to #754 which still reinstalled the package each build. This sets `cmake_minimum_required(3.24)` to match MRC and get consistent policies for the relative/absolute depfile options.
Also fixes some previous merge issues.
=> Fix absolute depfile causing python package to reinstall each build

tests/test_message_meta.py
We had two tests that set values on row 3, however we now randomly duplicate the index, causing a situation where 3 might not exist in the index.
=> Fix intermittent test failure in tests/test_message_meta.py

examples/abp_pcap_detection/abp_pcap_preprocessing.py, morpheus/messages/multi_message.py, tests/test_multi_message.py
* Work-around for change in cudf introduced by https://github.com/rapidsai/cudf/issues/10226
* Fix handling of indexes and offsets in `examples/abp_pcap_detection/abp_pcap_preprocessing.py`
* Cudf will throw a different exception on a series of strings than a list of strings
fixes #790
=> Fix abp_pcap_detection example

morpheus/stages/postprocess/filter_detections_stage.py
Fixes the printing of the type
=> Fix debug log message caused by breaking the long string

ci/conda/recipes/morpheus/meta.yaml, examples/digital_fingerprinting/production/docker-compose.yml
Currently the DFP containers build from morpheus-23.01 by default, this just changes the default to 23.03
Add scikitlearn & dill to release env fixes #814
=> Set default DFP container version to 23.03

morpheus/_lib/cmake/libraries/cudf_helpers.cmake
We don't have direct control over this code, so no reason to see gcc warnings about it.
This doesn't remove the `'UNEQUAL' redeclared` warning which appears to be issued by Cython itself without the ability to suppress it.
fixes #757
=> Suppress volatile warning when building code generated by Cython

.gitmodules, ci/release/update-version.sh, ci/scripts/github/checks.sh, ci/scripts/version_checks.sh, docs/source/cloud_deployment_guide.md, docs/source/getting_started.md
This PR adds a new script `ci/release/update-version.sh` to help with updating the version numbers when making a new release. It also adds a CI check to ensure the versions are correct moving forward.
Note, these follow similar files in the RAPIDS org. For example, in cudf: https://github.com/rapidsai/cudf/blob/branch-23.06/ci/release/update-version.sh
Similar to MRC PR: https://github.com/nv-morpheus/MRC/pull/314
=> Adding an `update-version.sh` script and CI check to keep versions up to date

.github/workflows/ci_pipe.yml, .github/workflows/pull_request.yml, ci/runner/Dockerfile, docs/source/conf.py
This PR is follows the MRC PR: https://github.com/nv-morpheus/MRC/pull/313 which removes the explicit dependency on `libnvidia-ml.so` which allows us to no longer need the driver installed in our CI runner.
This allows us to use the `gpu-v100-latest-1` tag to stay up to date with the CI images.
@jjacobelli for Viz
=> Removing explicit driver install from CI runner

morpheus/_lib/include/morpheus/io/serializers.hpp, morpheus/_lib/src/io/serializers.cpp, morpheus/_lib/src/stages/write_to_file.cpp, morpheus/_lib/tests/test_file_in_out.cpp
* Allows for writing JSON data in C++ without acquiring the gil
* Uses new C++ JSON writer in cudf added in v23.02
* Technically this is a breaking as the signature of the `df_to_json`  functions changed from accepting  `MutableTableInfo&` to `const TableInfo&`, however this isn't a breaking change for users of the Python API
fixes #761
=> Use new cudf C++ json writer

.github/workflows/ci_pipe.yml
This PR is updating the runner labels to use ARC V2 self-hosted runners for GPU jobs. This is needed to resolve the auto-scalling issues.
=> Use ARC V2 self-hosted runners for GPU jobs

morpheus/models/dfencoder/autoencoder.py, tests/dfencoder/test_autoencoder.py
The `fit` (`get_anomaly_score_losses`) function in dfencoder encounters an error when no categorical feature is present in the feature set. This PR adds the necessary checks in `get_anomaly_score_losses` to ensure the code runs with or without categorical features.
Fixes #858
=> Fix `get_anomaly_score_losses` in dfencoder to work without categorical features

.github/workflows/label-external-issues.yml
This PR updates the secret in the external issue labeler GHA to use one with permissions to see who is a member of `nv-morpheus`.
It also auto-labels new external discussions with the `Needs Triage` label as well.
=> [ENH] Label External Issues: Update secret, add discussions

.github/workflows/label-external-issues.yml
This PR rewrites the action from `graphQL` to `gh cli`. 
~Functionality should remain the same.~ Removed discussions since they're not supported by the gh cli.
=> [ENH] Change external labeler to use the GH CLI for fine-grained token support

.github/workflows/label-external-issues.yml
The graphQL API prefers to return `CONTRIBUTOR` over `MEMBER` and `OWNER`. This PR adds the exclusion of `CONTRIBUTOR` for labeling with https://github.com/nv-morpheus/Morpheus/labels/Needs%20Triage
=> Add CONTRIBUTOR to triage label exception

scripts/compile.sh
Fixes a bug where `CMAKE_ARGS` was being enclosed in extra quotes, causing `CMAKE_ARGS` to be evaluated a single filename, which was not found.
Closes #906
=> remove unnecessary quotes from CMAKE_ARGS expression

morpheus/stages/output/compare_dataframe_stage.py
* Fixes intermittent segfault in `CompareDataFrameStage` and `ValidationStage`
=> Fix race condition in CompareDataFrameStage

examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_file_batcher_stage.py, examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py
Currently, the DFP pipeline simulates time by breaking incoming messages up by a specific period and processing each period independently. This makes it impossible to process all of the incoming data at once for batch mode with a single trained model.
This PR adds a few things:
- If `DFPFileBatcherStage.period == None`, then all messages will be processed in a single batch, instead of per period
- Fixes how periods were handled to work with counts
- Before, `"D"` would work as expected but `"5D"` would not. This was due to using `to_period`
- The `DFPFileBatcherStage.sampling_rate_s` property was deprecated in favor of a more general `sampling` property
- This property can support different values
- If its a string, the value is interpreted as a frequency. The first row for each frequency …
=> Improve DFP period functionality to allow for better sampling and ignoring period

.github/workflows/label-external-issues.yml
Sometimes `github.event.issue.authorAssociation` in the workflow will pick `COLLABORATOR` for our team members. This PR adds `COLLABORATOR` to the list of association Enums that we skip the triage label action for.
=> Add COLLABORATOR to exclusion in label-external-issues.yml

morpheus/pipeline/pipeline.py, morpheus/pipeline/receiver.py, morpheus/pipeline/single_port_stage.py, morpheus/pipeline/stream_wrapper.py, tests/test_nonlinear_pipeline.py
This PR fixes a long overdue placeholder exception from back when we were still using `streamz`. If a user configured multiple upstream stages to a single downstream port, then you would get a `NotImplementedError`. For example, the following would cause an exception:
```python
source1 = pipe.add_stage(InMemorySourceStage(config, [filter_probs_df]))
source2 = pipe.add_stage(InMemorySourceStage(config, [filter_probs_df]))
sink_stage = pipe.add_stage(InMemorySinkStage(config))
pipe.add_edge(source1, sink_stage)
pipe.add_edge(source2, sink_stage)
```
Also adds a simple tests to run the above scenario.
=> Fixing multi-sender stage configurations

docker/Dockerfile, docker/conda/environments/cuda11.8_dev.yml, tests/test_downloader.py
* Restore pin for camouglage v0.9 in Dockerfile, newer versions are incompat
* Skip tests for `morpheus.utils.downloader` when `dask.distributed` is not installed.
* Install `cuda-toolkit` not `cudatoolkit`
=> Fix build issues & tests

docker/Dockerfile, docker/conda/environments/cuda11.8_dev.yml
- Update `.bashrc` in container to activate `morpheus` conda environment. Dockerfile was previously using `sed` to replace existing `conda activate base` with `conda activate morpheus`. Base image no longer has `conda activate base` so now just appending `conda activate morpheus` to `.bashrc`.
Fixes #968
=> Update .bashrc in container to activate morpheus conda environment

docs/source/developer_guide/guides.md, docs/source/developer_guide/guides/1_simple_python_stage.md, docs/source/developer_guide/guides/2_real_world_phishing.md, docs/source/developer_guide/guides/3_simple_cpp_stage.md, docs/source/developer_guide/guides/4_source_cpp_stage.md
* Add info on building the C++ examples
* Each guide specifies where the code lives under the examples dir
fixes #793
=> Document how to build the examples

morpheus/_lib/include/morpheus/modules/data_loader_module.hpp, morpheus/_lib/src/modules/data_loader_module.cpp, morpheus/_lib/tests/modules/test_data_loader_module.cpp
MRC PR https://github.com/nv-morpheus/MRC/pull/328 had some breaking changes. While minimal, they needed to be reflected in the Morpheus build.
=> Fixing build with MRC breaking changes

ci/conda/recipes/morpheus/meta.yaml
- Update conda recipe to use `cuda-toolkit` for build
- `cuda-toolkit` no longer gets installed as run dependency by `cudf` (via `cuda-python`)
=> Use cuda-toolkit in release container build

ci/conda/recipes/morpheus/meta.yaml, docker/Dockerfile, docker/conda/environments/cuda11.8_dev.yml, docker/conda/environments/cuda11.8_examples.yml, models/mlflow/docker/Dockerfile, models/mlflow/docker/conda/mlflow-env.yml
There were some post release CVE issues from NGC after 23.03. These changes address those formally.
=> Bring forward some CVE fixes from 23.03 release

models/model-cards/gnn-fsi-model-card.md, models/model-cards/gnn-fsi-modelcard.md
Add modelcard++ for the GNN FSI model.
=> GNN FSI modelcard++

tests/benchmarks/e2e_test_configs.json, tests/benchmarks/test_bench_e2e_pipelines.py
- Move hard-coded glob (inside `MORPHEUS_ROOT`) for CloudTrail AE training data to `e2e_test_configs.json`.
- Fix CloudTrail AE training data glob to point to training data instead of validation/inference data. This will result in longer pipeline run times because training data used by pipeline will now be larger.
Fixes #1005
=> Move hard-coded path in E2E benchmarks to config json

ci/conda/recipes/morpheus/meta.yaml, ci/conda/recipes/run_conda_build.sh, docker/Dockerfile, docker/conda/environments/cuda11.8_dev.yml, docker/conda/environments/requirements.txt, models/training-tuning-scripts/log-parsing-models/log-parsing-training.ipynb, models/training-tuning-scripts/log-parsing-models/requirements.txt, models/training-tuning-scripts/phishing-models/requirements.txt, models/training-tuning-scripts/root-cause-models/requirements.txt, models/validation-inference-scripts/dfp-models/requirements.txt, models/validation-inference-scripts/phishing-models/requirements.txt, models/validation-inference-scripts/root-cause-models/requirements.txt, setup.py
- Update docker containers and conda recipe/environments to install pytorch 2.0.1 conda package
- Also update torch version for training-tuning scripts/notebooks
Closes #1008
=> Upgrade to pytorch 2.0.1 conda package

setup.py
- Remove `PIP_FIND_LINKS` for torch in `setup.py`. This was missed by PR #1015 which only removed it in `docker/conda/environments/requirements.txt`.
=> Remove PIP_FIND_LINKS for torch from setup.py

morpheus/stages/postprocess/generate_viz_frames_stage.py, morpheus/utils/producer_consumer_queue.py
Due to changes in `asyncio` in Python 3.10, we needed to remove the `loop` parameter from several API calls. See [here](https://blog.teclado.com/changes-to-async-event-loops-in-python-3-10/) for more info.
Fixes #1031
=> Remove `loop` from several `asyncio` API calls

examples/digital_fingerprinting/fetch_example_data.py
* Fix bug by using `s3fs.S3FileSystem.get_file` instead of `s3fs.S3FileSystem.get`
* Apply pylint fixes
fixes #1047
=> Fix fetch_example_data.py to work with s3fs v2303.6

docker/conda/environments/cuda11.8_dev.yml
To work with the change from MRC PR https://github.com/nv-morpheus/MRC/pull/353, we need to use `libgrpc` instead of `grpc-cpp` in our conda environments since they changed the package name.
=> Changing GRPC requirement from `grpc-cpp` to `libgrpc`

ci/conda/recipes/morpheus/meta.yaml, docker/Dockerfile, docker/build_container.sh, docker/conda/environments/cuda11.8_dev.yml
This PR adds a runtime restriction on `sqlalchemy<2.0` because version 2.0 is incompatible with `pandas=1.3`. See [here](https://stackoverflow.com/a/75282604) for more information.
The runtime restriction was missing even though it was included in the conda dev dependencies.
Included in this PR are changes to remove Git LFS from the base image and only install it in later stages used to build the conda package.
=> Setting `sqlalchemy` restrictions to be compatible with our version of `pandas`

tests/examples/gnn_fraud_detection_pipeline/conftest.py, tests/examples/gnn_fraud_detection_pipeline/test_classification_stage.py, tests/examples/gnn_fraud_detection_pipeline/test_graph_sage_stage.py
* thd `manual_seed` fixture for `gnn_fraud_detection_pipeline` is now set to autouse
* fixes #1164
=> Make manual_seed an autouse fixture for gnn_fraud_detection_pipeline tests

README.md, tests/_utils/kafka.py, tests/test_kafka_source_stage_pipe.py
* Fixes intermittent failures in `tests/test_kafka_source_stage_pipe.py::test_kafka_source_commit`
* The test checked the offsets in a stage, however the C++ impl for the source stage performs a commit after calling `on_next`. This also limited us to only testing sync commits.
* Updated test performs the offset check after the pipeline completes when we can be assured that all commits have completed.
Fxies #1217
=> Fix Kafka offset checking test

.github/workflows/ci_pipe.yml
* Test stage was updated a while ago to perform its own builds.
Closes #1213
=> CI test stage no longer depends on build stage

examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_training_pipe.py, examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py
- Update autoencoder `model_kwargs` in DFP training module/stage to match recently renamed constructor parameters in autoencoder.
=> Update DFP training model_kwargs

morpheus/loaders/sql_loader.py, morpheus/utils/control_message_utils.py
- Updated SQL loader to utilize connections from the pool.
- Fixed control message utility variable referenced before assignment error.
closes #1237 #1235
=> [BUG] Fix Control Message Utils & SQL Max Connections Exhaust

ci/conda/recipes/morpheus/meta.yaml, ci/scripts/github/common.sh, docker/conda/environments/cuda11.8_dev.yml, docker/conda/environments/cuda11.8_examples.yml, models/mlflow/docker/conda/mlflow-env.yml, morpheus/loaders/sql_loader.py, morpheus/utils/control_message_utils.py, tests/test_kafka_source_stage_pipe.py
Resolved conflicts from forward merger PR#1241
=> Forward-merge branch-23.07 to branch-23.11 [resolved conflicts]

examples/digital_fingerprinting/production/morpheus/dfp/utils/dfp_arg_parser.py, examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py, examples/digital_fingerprinting/production/morpheus/dfp_duo_pipeline.py, examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_batch_pipeline.py, examples/digital_fingerprinting/production/morpheus/dfp_integrated_training_streaming_pipeline.py, morpheus/controllers/mlflow_model_writer_controller.py
=> [DRAFT] Add model and experiment template 'click' options to dfp example pipelines, and make model names Databricks compatible.

morpheus/utils/control_message_utils.py
Add `@wraps` decorator to `cm_skip_processing_if_failed` to allow docstrings for wrapped methods to generate documentation.
=> Fix documentation for morpheus.loaders.sql_loader

ci/scripts/github/test.sh, pyproject.toml, tests/_utils/__init__.py, tests/conftest.py, tests/test_milvus_vector_db_service.py, tests/test_milvus_write_to_vector_db_stage_pipe.py
* Builds on PR #1273
* Skip milvus tests by default requiring a `--run_milvus` flag, similar to the kafka tests which require the `--run_kafka` flag.
* Milvus takes over a minute just to start up, and the tests require an additional three minutes. Requiring four minutes just to run the milvus tests alone, while the rest of the slow tests take only a minute and a half.
* Consolidate milvus related fixtures.
* Specify an explicit temp dir as the storage location for milvus, ensuring we always start with an empty database.
- When the PR is ready for review, the …
=> Skip milvus tests by default

docker/conda/environments/cuda11.8_dev.yml, docker/conda/environments/cuda11.8_examples.yml, examples/llm/vdb_upload/README.md, examples/llm/vdb_upload/run.py, morpheus/stages/input/rss_source_stage.py
* Add a minimal readme with triton command
* Remove pre_calc_embeddings flag and make this enabled by default (pipe wasn't working without it)
* Update model name and feature length size.
* Add a `--stop_after` flag allowing the pipeline to be quickly tested
* Fix `stop_after` functionality in RSS source stage
* Add LLM dependencies to kitchen-sink examples yaml
* Widen networkx version restriction to match requirements for langchain which is incompat with networkx 3.0+
* Builds on/includes changes from PRs #1273 & #1284
- When the PR is ready for review, the …
=> Misc updates & fixes for the vdb_upload pipeline

examples/llm/common/llm_engine_stage.py
* Set `pe_count=1` a value of 2 was causing Morpheus to crash.
Closes #1291
=> Fix LLMEngineStage crashes

examples/digital_fingerprinting/production/morpheus/dfp_azure_pipeline.py
=> Make dfp_azure_pipeline inference output file configurable.

docs/conda_docs.yml, docs/source/conf.py, docs/source/examples/llm/README.md, docs/source/examples/llm/agents/README.md, docs/source/examples/llm/completion/README.md, docs/source/examples/llm/index.rst, docs/source/examples/llm/rag/README.md, docs/source/examples/llm/vdb_upload/README.md, morpheus/_lib/llm/__init__.pyi, morpheus/_lib/llm/module.cpp, morpheus/_lib/src/llm/utils.cpp, morpheus/_lib/src/stages/kafka_source.cpp
* Exclude `PYBIND11_NAMESPACE` namespace from C++ documentation builds
* Define `DOXYGEN_SHOULD_SKIP_THIS` macro as recommended in https://www.doxygen.nl/manual/faq.html#faq_code
* Define `MORPHEUS_EXPORT` as an empty macro during doxygen builds to prevent doxygen parsing errors.
* Escape occurrences of `*` in docstrings as Sphinx interprets this as the start of a bold section.
* Disable Pybind11 auto-generated function signatures from being generated for `LLMNode`, as these created an error for Sphinx as it couldn't handle the overloaded signatures, instead explicitly define a docstring.
* Mock the `langchain` module during sphinx builds as it is not installed in the default env.
* 
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/s …
=> Fix documentation builds

morpheus/service/milvus_vector_db_service.py, tests/test_milvus_vector_db_service.py
Removed `with_collection_lock` related tests from Milvus and added notes to function documentation.
Closes #1326 
=> Removed Mutex Related Milvus Tests

morpheus/_lib/llm/__init__.pyi, morpheus/_lib/llm/module.cpp
* The auto-generated docstrings created by pybind11 for `add_node` created errors for Sphinx.
* Disabling them, and adding explicit docstrings fixes the Sphinx issue, but causes stubgen to omit including `add_node` from the `pyi` file.
* This PR works-around both issues by removing the overload, and handling the difference in the lambda method.
Closes #1331
=> Remove overload of 'add_node' handling null inputs in lambda

morpheus/llm/nodes/extracter_node.py, tests/_utils/llm.py, tests/io/test_data_record.py, tests/llm/nodes/test_extractor_node.py, tests/llm/test_extractor_simple_task_handler_pipe.py
* Adds docstrings and tests for ExtracterNode
* Update `execute_node` test helper to add a task and control message to the context
* Update `tests/io/test_data_record.py` to store test files in a temporary directory, prevents them from being left in the repo dir when tests are halted.
* Rename `tests/llm/task_handlers/test_simple_task_handler_pipe.py` -> `tests/llm/test_extractor_simple_task_handler_pipe.py` to reflect the fact that an end-to-end test for `ExtracterNode` requires also testing `SimpleTaskHandler`
Closes #1277 
- When the PR is ready for review, the …
=> Docstrings and tests for ExtracterNode

examples/digital_fingerprinting/production/Dockerfile, examples/digital_fingerprinting/production/conda_env.yml
- Update `nodejs` in DFP container to match version in Morpheus dev conda environment.
- Update `jupyterlab_nvdashboard` version to fix the following error seen in jupyterlab startup.
```
[W 2023-11-06 23:01:38.953 ServerApp] jupyterlab_nvdashboard | extension failed loading with message: ExtensionLoadingError('_load_jupyter_server_extension function was not found.')
jupyter  |     Traceback (most recent call last):
jupyter  |       File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 358, in load_extension
jupyter  |         extension.load_all_points(self.serverapp)
jupyter  |       File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 230, in load_all_points
jupyter  |         return …
```
=> DFP container updates

docker/conda/environments/cuda11.8_dev.yml, morpheus/service/vdb/milvus_vector_db_service.py, morpheus/service/vdb/vector_db_service.py, tests/test_milvus_vector_db_service.py
- Updated tests to mitigate bug from `milvus==2.3.2`
- Exposed `release_resource` API
- Removed tests that verifies `collection_lock` mechanism
Closes #1345 
=> Updated Milvus Tests and Exposed `release_resource` API

morpheus/_lib/src/llm/llm_node_runner.cpp, morpheus/_lib/tests/CMakeLists.txt, morpheus/_lib/tests/llm/test_llm_node_runner.cpp, morpheus/_lib/tests/llm/test_llm_task.cpp, morpheus/_lib/tests/llm/test_llm_task_handler_runner.cpp
- C++ unit tests for LLMNodeRunner, LLMTaskHandlerRunner and LLMTask
- Fix check for duplicate input names in LLMNodeRunner
=> C++ unit tests for LLMNodeRunner, LLMTaskHandlerRunner and LLMTask

examples/llm/agents/kafka_pipeline.py, examples/llm/common/utils.py, examples/llm/rag/persistant_pipeline.py, examples/llm/rag/run.py, examples/llm/rag/standalone_pipeline.py, morpheus/stages/input/rss_source_stage.py, tests/llm/conftest.py, tests/llm/services/conftest.py, tests/llm/services/test_llm_service_pipe.py, tests/llm/test_completion_pipe.py, tests/llm/test_rag_standalone_pipe.py, tests/tests_data/service/milvus_rss_data.json
* Add end-to-end tests for completion and stand-alone rag pipelines
* Optionally support openai as a backend for the rag pipeline
* Add `--embedding_size` to stand-alone rag pipeline, removing previously hard-coded value
* Fix evaluation of `stop_after` argument in RSS source stage.
* Relocate some fixtures from `tests/llm/services/conftest.py` to `tests/llm/conftest.py`
* Currently checks are failing for `examples/llm/rag/persistant_pipeline.py`, due to `SplitStage` not being updated.
- When the PR is ready for review, the documentation is up to date with these …
=> Add end-to-end tests for completion and stand-alone rag pipelines

tests/llm/test_rag_standalone_pipe.py
* The two end-to-end integration tests for the RAG pipeline required a running Milvus instance, but didn't have the `milvus` test marker.
=> Add missing milvus mark for two tests which require milvus

tests/common/test_http_server.py
* Wait up to 30 seconds for the callback function to be invoked prior to stopping the server
Closes #1370
=> Draft: fix for test_simple_request

examples/llm/common/web_scraper_stage.py, examples/llm/vdb_upload/pipeline.py
Made the `enable_cache` accessible as a parameter
=> Caching Flag Accessible as a Parameter

tests/llm/test_vdb_upload_pipe.py, tests/tests_data/service/milvus_rss_data.json
* Update mocks to reflect that When caching is disabled web-scraper uses requests not requests_cache.
* Revert accidental change to `tests/tests_data/service/milvus_rss_data.json` during merge conflicts
=> Fix test_vdb_upload_pipe

examples/abp_nvsmi_detection/README.md, morpheus/_lib/src/stages/preprocess_fil.cpp
* Fixes a race condition where the `fix_bad_columns` method attempts to fix the same column more than once per-DF, resulting in a failure on the second attempt.
=> Fix race condition in the C++ impl for the pre-process fil stage

morpheus/pipeline/pipeline.py, morpheus/stages/postprocess/generate_viz_frames_stage.py
Due to the changes in #1233, the pipeline shutdown process has been slightly altered. This updates the viz demo to shutdown correctly without error. Also added support for exiting on Ctrl+C
Fixes #1391
=> Fix the SID Viz workflow shutdown process with the new pipeline shutdown process

morpheus/cli/commands.py, tests/test_cli.py
* Allows manually seeding random number generators from the CLI via either `--manual_seed` or setting the `MORPHEUS_MANUAL_SEED` environment variable.
* Makes testing example CLI pipelines easier.
Closes #1211
=> Add a --manual_seed flag to the CLI

ci/conda/recipes/morpheus/meta.yaml, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/dev_cuda-118_arch-x86_64.yaml, dependencies.yaml, docker/conda/environments/cuda11.8_dev.yml, examples/digital_fingerprinting/production/morpheus/benchmarks/conftest.py, tests/benchmarks/conftest.py
+ Replace `GPUtil` with `pynvml` to collect GPU stats for benchmark reports.
+ Remove `GPUtil` from dependency yaml's. `pynvml` is already installed via `nvtabular`.
Closes #1446 
=> Replace GPUtil with pynvml for benchmark reports

morpheus/utils/logger.py
- Fixes bug in logger where it was looking for `json` instead of `.json` when passing JSON config file.
Fixes #1470
=> Fix expected JSON config file extension in logger

morpheus/models/dfencoder/autoencoder.py, tests/dfencoder/test_autoencoder.py, tests/dfencoder/test_dfencoder_distributed_e2e.py
This PR addresses an issue in the dfencoder model related to its convergence behavior. Previously, the model exhibited difficulty in converging when trained exclusively with numerical features. 
This PR fixes the way different loss types are combined in the model's loss function to ensure that backpropagation works correctly.
Note: This may alter the exact values resulting from calling `fit()` on the model. Before, categorical features were weighted much higher than binary or numerical categories (all numerical features shared a combined weight of 1, all binaries features shared a combined weight of 1, and each categorical feature had a weight of 1). Now all features are weighted equally which may impact the trained weights.
Closes #1455
=> Fix Loss Function to Improve Model Convergence for `AutoEncoder`

morpheus/pipeline/boundary_stage_mixin.py, morpheus/pipeline/pipeline.py, morpheus/stages/boundary/linear_boundary_stage.py, tests/pipeline/test_pipeline.py
* Creates a new `BoundaryStageMixin` class 
* Allowing `LinearBoundaryEgressStage` and `LinearBoundaryIngressStage` to share a common class and be distinguished from other stages
Closes #638 
=> Create a base mixin class for ingress & egress stages

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/dev_cuda-118_arch-x86_64.yaml, dependencies.yaml, docker/conda/environments/cuda11.8_dev.yml
=> Pin pytest to <8

morpheus/_lib/include/morpheus/utilities/cupy_util.hpp, morpheus/_lib/src/utilities/cupy_util.cpp, tests/test_tensor_memory.py
* Remove static reference to the `cupy` python module in `CupyUtil` which was causing a segfault on interpreter shutdown.
=> Fix intermittent segfault on interpreter shutdown

morpheus/pipeline/pipeline.py, morpheus/pipeline/stage.py, morpheus/pipeline/stage_base.py, tests/pipeline/test_pipeline.py
- Moves `start_async` from `Stage` to `StageBase` to make it available to source stages.
- Adds tests for source stage `start_async` and `on_start`. 
Closes #1522
=> Make `start_async()` available to source stages

morpheus/_lib/include/morpheus/objects/mutable_table_ctx_mgr.hpp, morpheus/_lib/include/morpheus/objects/table_info.hpp, morpheus/_lib/include/morpheus/stages/preprocess_fil.hpp, morpheus/_lib/src/messages/multi.cpp, morpheus/_lib/src/objects/mutable_table_ctx_mgr.cpp, morpheus/_lib/src/objects/table_info.cpp, morpheus/_lib/src/stages/preprocess_fil.cpp, morpheus/_lib/tests/messages/test_dev_doc_ex3.cpp
* Switch to using a `unique_ptr` to hold the python object
* Random IWYU fixes.
Closes #1533
=> Fix memory leak in the mutable dataframe checkout/checkin code

morpheus/llm/services/openai_chat_service.py, tests/llm/services/test_openai_chat_client.py, tests/llm/services/test_openai_chat_service.py
* Avoids momentary rate limit errors
=> Expose max_retries parameter to OpenAIChatService & OpenAIChatClient

morpheus/_lib/common/__init__.pyi, morpheus/_lib/common/module.cpp, morpheus/_lib/include/morpheus/objects/file_types.hpp, morpheus/_lib/include/morpheus/stages/file_source.hpp, morpheus/_lib/src/objects/file_types.cpp, morpheus/_lib/src/stages/file_source.cpp, morpheus/_lib/stages/__init__.pyi, morpheus/_lib/stages/module.cpp, tests/common/test_determine_file_type.py, tests/test_file_in_out.py
* The type hint for the `filename` argument to the `FileSourceStage` is `pathlib.Path`, however this is incompatible with the C++ impl and the `determine_file_type` method.
Closes #1530
=> Fix pathlib.Path support for FileSourceStage

morpheus.code-workspace, morpheus/llm/services/llm_service.py, morpheus/llm/services/nemo_llm_service.py, morpheus/llm/services/openai_chat_service.py, tests/_utils/environment.py, tests/conftest.py, tests/llm/conftest.py, tests/llm/services/test_llm_service_pipe.py, tests/llm/services/test_nemo_llm_client.py, tests/llm/services/test_nemo_llm_service.py, tests/llm/services/test_openai_chat_client.py, tests/llm/test_completion_pipe.py
- Adds the ability to retry NeMo failures more than one time
- Adds an argument to configure the retry count
- Adds support for proxying requests to the NeMo service using the `NGC_API_BASE` environment variable
- Changes the API for the base `LLMService` to improve the type hints and allow arguments other than strings to be used.
=> Add retry logic and proxy support to the NeMo LLM Service

examples/digital_fingerprinting/production/morpheus/benchmarks/test_bench_e2e_dfp_pipeline.py
- Fix call to `configure_logging` in `test_bench_e2e_dfp_pipeline.py`.
Closes #1552
=> Fix `configure_logging` in DFP benchmarks

examples/digital_fingerprinting/production/mlflow/Dockerfile, examples/digital_fingerprinting/production/morpheus/dfp/utils/config_generator.py
- Update `mlflow_writer_options` in DFP config generator to use Python 3.10 (from 3.8) for model's conda environment.
- Update base image of MLflow container to Python 3.10.
Closes #1565
=> Update MLflow in Production DFP example to use Python 3.10

examples/digital_fingerprinting/production/morpheus/dfp/utils/model_cache.py
- Small update to handle MLflow `search_registered_models` results using file URI.
Closes #1574
=> Update DFP MLflow ModelManager to handle model retrieval using file URI

morpheus/modules/file_batcher.py, tests/modules/test_file_batcher.py
- Update `file_batcher`module to use documented module config key `iso_date_regex_pattern` instead of `batch_iso_date_regex_pattern`.
- Allow override of `iso_date_regex_pattern` with control message.
- Add tests for `file_batcher` module
Closes #1576 
Closes #1577
=> Fix `iso_date_regex_pattern` config in `file_batcher` module and allow override

conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/dev_cuda-121_arch-x86_64.yaml, conda/environments/examples_cuda-121_arch-x86_64.yaml, conda/environments/model-utils_cuda-121_arch-x86_64.yaml, conda/environments/runtime_cuda-121_arch-x86_64.yaml, dependencies.yaml
This removes the `defaults` channel from `dependencies.yml` to use only `conda-forge`
=> Remove the defaults channel from `dependencies.yml`

examples/digital_fingerprinting/production/morpheus/dfp/utils/config_generator.py, morpheus/modules/file_batcher.py, tests/examples/digital_fingerprinting/utils/test_config_generator.py, tests/modules/test_file_batcher.py
* Fixes an issue where the `--start_time` flag was being ignored
* Prior to nv-morpheus/MRC#451 the `datetime` objects being stored in the config were being serialized to json null, after that change an exception was raised.
Closes #1590
=> Serialize datetime objects into the module config

docs/source/cloud_deployment_guide.md, docs/source/developer_guide/contributing.md, docs/source/getting_started.md, examples/gnn_fraud_detection_pipeline/README.md, examples/llm/vdb_upload/README.md
* Set new minimums to Volta (compute 7), cuda-12.1
* Remove minimum driver version, and instead just document our cuda version.
Closes #1464
=> Update minimum compute requirements to Volta

conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/dev_cuda-121_arch-x86_64.yaml, conda/environments/examples_cuda-121_arch-x86_64.yaml, conda/environments/runtime_cuda-121_arch-x86_64.yaml, dependencies.yaml
* Fixes `ModuleNotFoundError: No module named 'databricks_cli'` issue
Closes #1600
=> Fix for databricks_cli import error

morpheus/_lib/include/morpheus/objects/memory_descriptor.hpp, morpheus/_lib/src/objects/memory_descriptor.cpp
* Move `MemoryDescriptor` to the morpheus namespace
* Technically a C++ API breaking change, although I can't imagine this impacting any users.
Closes #1601
=> Move MemoryDescriptor to the morpheus namespace

ci/scripts/download_kafka.py
* The download for kafka 3.4.1 has been removed.
* This doesn't impact Morpheus itself, but impacts developers wishing to run Kafka integration tests. 
Closes #1613
Note: The CI runner images have our previous version of kafka pre-downloaded, such that this change isn't actually tested in CI. I did test this locally in a fresh conda env.
=> Switch to kafka 3.5.2

ci/conda/recipes/morpheus/meta.yaml, conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/dev_cuda-121_arch-x86_64.yaml, conda/environments/examples_cuda-121_arch-x86_64.yaml, conda/environments/runtime_cuda-121_arch-x86_64.yaml, dependencies.yaml, examples/digital_fingerprinting/production/conda_env.yml, examples/digital_fingerprinting/production/mlflow/Dockerfile, models/mlflow/README.md, models/mlflow/docker/Dockerfile
* Avoids two related CVEs involving MLflow
* Update mlflow-triton documentation 
=> Update mlflow to avoid  CVE-2024-27132 and CVE-2024-27133

CHANGELOG.md, ci/conda/recipes/morpheus/meta.yaml, ci/scripts/download_kafka.py, conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/dev_cuda-121_arch-x86_64.yaml, conda/environments/examples_cuda-121_arch-x86_64.yaml, conda/environments/runtime_cuda-121_arch-x86_64.yaml, dependencies.yaml, examples/digital_fingerprinting/production/conda_env.yml, examples/digital_fingerprinting/production/mlflow/Dockerfile, models/mlflow/README.md, models/mlflow/docker/Dockerfile, morpheus/_lib/include/morpheus/objects/memory_descriptor.hpp, morpheus/_lib/src/objects/memory_descriptor.cpp
This is the PR containing all of the changes for the 24.03.01 Hotfix
=> [RELEASE] Morpheus v24.03.01 Hotfix

ci/check_style.sh
conda dropped support for the --force flag to conda env create. This changes that flag name to --yes.
See https://github.com/conda/conda/blob/main/CHANGELOG.md#2430-2024-03-12 and https://github.com/rapidsai/miniforge-cuda/pull/63 for more info.
=> Use conda env create --yes instead of --force

.devcontainer/Dockerfile
Closes https://github.com/nv-morpheus/Morpheus/issues/1624, where the devcontainer fails to build due to a mis-typed base container.
=> Fix a typo in the devcontainer base image

morpheus/_lib/include/morpheus/objects/dtype.hpp, morpheus/_lib/src/objects/dtype.cpp, morpheus/_lib/tests/CMakeLists.txt, morpheus/_lib/tests/objects/test_dtype.cpp
- Update to `DType::from_numpy` to handle strings that identify `uint8` and `int8` dtypes
- Add unit tests for DType
- Update to throw invalid argument exceptions on invalid numpy typestr's.
Closes #1619
=> Fix `cupy_to_tensor` to also infer `uint8` and `int8` dtypes

docs/source/developer_guide/guides.md, docs/source/developer_guide/guides/3_simple_cpp_stage.md, docs/source/developer_guide/guides/4_source_cpp_stage.md, examples/developer_guide/4_rabbitmq_cpp_stage/README.md
* The Morpheus python package needs to be built and installed prior to building the examples, updated documentation to ensure `-DMORPHEUS_PYTHON_PERFORM_INSTALL=ON` is added 
=> Fix documentation for building examples

docs/source/extra_info/known_issues.md, examples/llm/cli.py, examples/llm/vdb_upload/pipeline.py, examples/llm/vdb_upload/vdb_utils.py, morpheus/io/utils.py, morpheus/service/vdb/milvus_vector_db_service.py, morpheus/stages/inference/inference_stage.py, morpheus/utils/type_aliases.py, tests/conftest.py, tests/io/test_io_utils.py, tests/test_milvus_vector_db_service.py, tests/tests_data/service/milvus_string_collection_conf.json
* Adds new helper methods to `morpheus.io.utils`, `cudf_string_cols_exceed_max_bytes` and `truncate_string_cols_by_bytes`
* When `truncate_long_strings=True` `MilvusVectorDBResourceService` will truncate all `VARCHAR` fields according to the schema's `max_length`
* Add `truncate_long_strings=True` in config for `vdb_upload` pipeline
* Set C++ mode to default for example LLM pipelines
* Remove issues 1650 & 1651 from `known_issues.md`
Closes #1650 
Closes #1651
=> Truncate strings exceeding max_length when inserting to Milvus

morpheus/llm/services/nvfoundation_llm_service.py
This PR standardizes the `NVIDIA_API_BASE` environment variable to `NVAI_BASE_URL` per discussion with maintainers. The new name better reflects the usage of this API for LLM-related tasks, and disambiguates it from other NVIDIA APIs we may need to use in the future.
I also updated the `NVFoundationLLMService` docstring with the new default base url used in the `langchain-nvidia-ai-endpoints` library.
=> Standardize `NVIDIA_API_BASE` environment variable to `NVAI_BASE_URL`

ci/conda/recipes/run_conda_build.sh, docker/build_conda_packages.sh, docker/run_container_dev.sh, morpheus/__init__.py
- Remove `pyarrow_hotfix` import
Closes #1691 
=> Remove `pyarrow_hotfix` import from `__init__.py`

docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md, examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_inference.py, examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_inference_stage.py, examples/digital_fingerprinting/production/morpheus/dfp/utils/model_cache.py
- Remove unused MLflow client arg from DFP inference stage and module implementations
- Add missing table of content items to Modular DFP guide
Closes #1693 
=> Remove unused MLflow client arg from DFP inference implementations

morpheus/llm/nodes/langchain_agent_node.py, morpheus/llm/services/nvfoundation_llm_service.py, tests/llm/nodes/test_langchain_agent_node.py
The agent model in the CVE pipeline sometimes runs into a parsing error that crashes the entire run. This PR adds the handling of such error by replacing it with a default failure sentence and logging the failure.
This PR also includes an addition of a default value for `NVAI_BASE_URL`.
=> Handling agent parsing error and adding a default value for NVAI_BASE_URL

morpheus/llm/services/openai_chat_service.py, tests/llm/services/conftest.py, tests/llm/services/test_openai_chat_client.py
- Update unit tests to handle recently added `api_key` and `base_url` parameters.
- Ensure log directory exists for logging FileHandler.
- Docstring update
=> Fixes and unit test updates to OpenAI client

.github/workflows/label-external-issues.yml, .github/workflows/project_automation_set_in_progress.yml, .github/workflows/project_automation_set_in_review.yml, .github/workflows/project_automation_set_roadmap.yml, .github/workflows/project_automation_sync_pr_issues.yml, .github/workflows/project_automation_track_pr_dates.yml
Removes all uses of `secrets.PROJECT_MANAGEMENT_PAT` to instead use the registered app and generate a token via the actions/create-github-app-token` action
=> Updating all uses of the `secrets.PROJECT_MANAGEMENT_PAT` to use a registered Github App

.github/workflows/pr.yaml
- This forces the `pr-builder` step to always be run. Since this is a required step in order to merge a PR, we want to make sure it is always run.
- This is needed since we skip some steps in CI by default which causes the pr-builder step to be skipped as well.
=> Always run the PR builder step even if others are cancelled

morpheus/_lib/include/morpheus/messages/meta.hpp, morpheus/_lib/src/messages/meta.cpp, morpheus/_lib/src/stages/preprocess_fil.cpp, morpheus/_lib/tests/messages/test_sliced_message_meta.cpp, morpheus/stages/preprocess/deserialize_stage.py
* Replace incorrect usage of `self.supports_cpp_node()` with `self._build_cpp_node()` in `DeserializeStage` to determine if a C++ impl should be used.
* Chose either `_stages.DeserializeControlMessageStage` or `_stages.DeserializeMultiMessageStage` based on the message type (likely this was a merge error).
* Add missing `get_info(const std::string&)` and `get_info(const std::vector<std::string>&)` to `SlicedMessageMeta` which indirectly fixes the cuda memory errors in #1747
Closes #1747
- When the PR is ready for review, the documentation is up to date with these …
=> Fixes for C++ impl for `DeserializeStage` and add missing `get_info` overloads to `SlicedMessageMeta`

examples/sid_visualization/README.md, examples/sid_visualization/run.py
* Remove unnecessary `pip install` from documentation as `compile.sh` does this by default now
* Set the viz pipeline to use C++ mode and remove single thread restriction
=> Misc improvements for sid_visualization example

examples/llm/vdb_upload/run.py, examples/llm/vdb_upload/vdb_config.yaml, examples/llm/vdb_upload/vdb_utils.py
* Disable shared memory by default since the C++ impl of the Triton stage doesn't support it
* Set the default source type to `rss` since it is the default, but defaulting to `None` causes any RSS related CLI flags to be ignored
Closes #1753
=> Disable shared memory by default, and fix `--stop_after` flag for `vdb_upload` example

examples/llm/rag/run.py, examples/llm/vdb_upload/run.py, examples/llm/vdb_upload/vdb_config.yaml, examples/llm/vdb_upload/vdb_utils.py
* PR #1617 replaced the hard-coded questions with a command-line-flag, however it was not given a default value nor was it marked as a required flag.
* Set the original question as the default value for the flag
Requires #1755
Closes #1757
=> Provide a default set of questions for the standalone RAG pipeline

examples/llm/main.py
The prog_name was appearing in help strings, ex:
```
python examples/llm/main.py vdb_upload --help
```
=> Remove setting of `prog_name`, this implies that an executable named `morpheus_llm` exists

examples/developer_guide/2_2_rabbitmq/README.md, examples/developer_guide/2_2_rabbitmq/read_simple.py, examples/developer_guide/4_rabbitmq_cpp_stage/README.md, examples/developer_guide/4_rabbitmq_cpp_stage/src/read_simple.py
The examples in `examples/developer_guide/2_2_rabbitmq` and `4_rabbitmq_cpp_stage` do not generate output files to `$MORPHEUS_ROOT` when following the README guidance. Change the output path to the root of repo to be consistent with other examples.
Closes #1754
=> Fix `RabbitMQ` output path

docker/Dockerfile, examples/digital_fingerprinting/production/Dockerfile
* Ensures that `/opt/conda/conda-bld` is a valid local conda channel. Without this any additional conda commands would error on an invalid conda channel (#1744). 
* Creates a new intermediate docker stage `runtime_conda_create` allowing it to make use of the read-only `/opt/conda/conda-bld` mount from `conda_bld_morpheus`. Then initializing the `/opt/conda/conda-bld` dir as a valid/empty local channel in the `runtime` stage.
* Update `examples/digital_fingerprinting/production/Dockerfile` to use conda with the libmamba solver.
Closes #1744
- When the PR is ready for …
=> Fix conda errors in release container

docs/README.md, docs/source/extra_info/troubleshooting.md
Closes #1767   
This pull request addresses the issue of missing notes for fixing documentation build failures. It adds a reference to the Building Documentation, and include more details to the Out of Date Build Cache section to help troubleshoot when the documentation build is unsuccessful.
=> Add troubleshooting reference for unsuccessful documentation builds

docs/source/developer_guide/contributing.md
* `jq` and `bc` are installed in the container by default
* `pip intall` is no longer needed as this is now executed by cmake
=> Remove out of date instructions from  `contributing.md`

docs/source/developer_guide/contributing.md, examples/gnn_fraud_detection_pipeline/README.md
Removes the following environment variables (that are never used during Morpheus build process) from documentation:
`PYTHON_VER`
`RAPIDS_VER`
`TRITONCLIENT_VERSION`
`CUDA_VER`
Closes #1781
=> Removes unused envioronment variables from Morpheus build docs

.devcontainer/docker-compose.yml
Add the `ransomw-model-short-rf` model to the triton volumes section of .devcontainer/docker-compose.yaml
Closes #1780 
=> Add ransomware model to devcontainer

docs/source/extra_info/known_issues.md, examples/llm/agents/README.md, examples/llm/agents/common.py, examples/llm/agents/kafka_pipeline.py, examples/llm/agents/run.py, examples/llm/agents/simple_pipeline.py
* Simple agents pipeline moved to `common.py` to be shared with the kafka pipeline
* Add `--bootstrap_servers` and `--topic` flags.
* Fix mis-named "Upload rate" monitor description with "Agent rate"
Closes #1791
=> Fix LLM Agents Kafka pipeline 

docker/Dockerfile
* Copy built documentation into the `docs` dir rather than the documentation source.
* Add a new docker stage `build_docs` 
Closes #1788
=> Install built documentation into release container

examples/llm/vdb_upload/langchain.py, examples/llm/vdb_upload/run.py, examples/llm/vdb_upload/vdb_config.yaml, examples/llm/vdb_upload/vdb_utils.py, tests/examples/llm/vdb_upload/test_vdb_utils.py
Currently CLI args always take precedence over Yaml config values, however since most of the CLI args have a default value in practice the Yaml config values are always ignored.
* Differentiate the explicit CLI args the user specified on the command line from the CLI args which include default values the user didn't specify. 
* Move default values out of the code blocks into global dicts
* Fix bug type-o causing Yaml schema definitions to be ignored.
* Resulting code is 100 lines shorter
Precedence order:
1. Explicit CLI args
2. Yaml config (if there is one)
3. Default CLI args
Closes #1752
- When the PR is ready for review, new or existing …
=> Fix merging of CLI args and Yaml configs in `vdb_upload` example

docs/source/conf.py
* This was needed to prevent documentation builds from loading merlin, which would require a GPU. 
=> Remove automock for merlin as we no longer have/use merlin

morpheus/pipeline/stage_decorator.py
* Improved type hints for both the input parameters and the return types
Closes  #1812
=> Improved type-hints for stage and source decorators

python/morpheus/setup.cfg
* Prevents isort from moving import os `_utils` to the third-party section
=> Fix isort config marking `_utils` as known first party

ci/scripts/common.sh, ci/scripts/python_checks.sh, morpheus.code-workspace, pyproject.toml, python/morpheus/setup.cfg
* Fixes isort vscode integration
* Fixes an issue where `tests` was listed in `src_paths` but this was expected to be relative to `python/morpheus`
=> Move isort settings into pyproject.toml 

.github/workflows/pr.yaml
CIs are failing because of #1736 not playing well with  https://github.com/rapidsai/shared-workflows/pull/237
As a stopgap I am reverting the changes in #1736
=> Revert PR_1736  "Always run the PR builder step even if others are cancelled"

.github/workflows/pr.yaml, conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/dev_cuda-121_arch-x86_64.yaml, conda/environments/examples_cuda-121_arch-x86_64.yaml, dependencies.yaml, examples/llm/vdb_upload/module/content_extractor_module.py
* Use pypdfium2 for PDF parsing
* Includes CI fix from PR #1860 
=> Replace pdf parsing libs

ci/scripts/common.sh, conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/dev_cuda-121_arch-x86_64.yaml, dependencies.yaml, docs/source/developer_guide/contributing.md, python/morpheus/morpheus/_lib/stages/__init__.pyi, python/morpheus/morpheus/_lib/stages/module.cpp, scripts/validation/val-run-pipeline.sh
* Ensure `BoostFibersMainPyAwaitable` is registered by importing `mrc.core.coro`
* Work-around for undefined symbol link error with c-ares
* Fix paths to data files in validation scripts
* Fix path to C++ files for CI checks
* Replace usage of `ie.` to avoid documentation CI error
Closes #1868
=> Fix `Unregistered type : mrc::pymrc::coro::BoostFibersMainPyAwaitable` error

python/morpheus/morpheus/stages/input/autoencoder_source_stage.py
=> Remove cloudtrail debug log from autoencoder source stage

.github/workflows/ci_pipe.yml
"CI Pipeline / check" job is only run on pull-requests so having that as a dependency was preventing the "packaging job" from happening on merges to the branch.
=> Drop 'CI Pipeline / Check' dependency from the 'package-core' job

examples/digital_fingerprinting/production/morpheus/dfp/modules/dfp_training.py
Fix DFP integrated training Azure pipeline, which indicates that `user_id` field is not attached to the `ControlMessage`.
Previously `user_id` is attached to `UserMessageMeta`, which is a subclass of `MessageMeta` that has an additional attribute. Now `UserMessageMeta` should be deprecated as all metadata can be attached directly to `ControlMessage`.
Closes #1893 
=> Fix DFP integrated training Azure pipeline

examples/llm/cli.py
* Import `pypdfium2` early to ensure the `atexit` registered by `pypdfium2` is invoked after our `after_pipeline` method is.
Closes #1864
=> Avoid memory leak warnings from `pypdfium2`

python/morpheus_llm/morpheus_llm/modules/output/write_to_vector_db.py, tests/test_milvus_write_to_vector_db_stage_pipe.py
* Fixes issue where the `WriteToVectorDBStage` catches/logs exceptions from the underlying database allowing failures to go unnoticed. 
* This is a behavior change, where previously errors were stored in the control message's metadata (although there was a bug in this part too so not all errors were stored in the metadata). 
Closes #1882
=> Update `WriteToVectorDBStage` to re-raise errors from the underlying database

tests/utils/test_shared_process_pool.py
This PR removes `SharedProcessPool.terminate()` related tests, which is generating stack traces that might cause remote-ci failure
Closes #1926 
=> Remove `SharedProcessPool.terminate()` related tests to avoid stack traces and blocking remote-ci

python/morpheus_llm/morpheus_llm/error.py, python/morpheus_llm/morpheus_llm/llm/nodes/langchain_agent_node.py, python/morpheus_llm/morpheus_llm/llm/services/nemo_llm_service.py, python/morpheus_llm/morpheus_llm/llm/services/nvfoundation_llm_service.py, python/morpheus_llm/morpheus_llm/llm/services/openai_chat_service.py, python/morpheus_llm/morpheus_llm/service/vdb/faiss_vdb_service.py, python/morpheus_llm/morpheus_llm/service/vdb/milvus_vector_db_service.py, tests/benchmarks/conftest.py, tests/benchmarks/test_bench_agents_simple_pipeline.py, tests/conftest.py, tests/llm/conftest.py, tests/llm/nodes/test_langchain_agent_node.py, tests/llm/services/conftest.py, tests/llm/services/test_nvfoundation_llm_service.py, tests/llm/test_agents_simple_pipe.py, tests/utils/test_shared_process_pool.py
* Ensure it is possible to run `pytest --run_slow` with only the dev yaml installed.
* Mark the tests in `tests/utils/test_shared_process_pool.py` as slow tests
* Remove redundant import error messages.
Closes [#1920](https://github.com/nv-morpheus/Morpheus/issues/1920)
=> Ensure that `pytest` is able to run without optional dependencies

examples/digital_fingerprinting/production/.env.sample, examples/digital_fingerprinting/production/mlflow/Dockerfile
* If I recall correctly we never got this working, and settled on sqlite
Closes [#1915](https://github.com/nv-morpheus/Morpheus/issues/1915)
=> Remove unused pymysql dependency from DFP mlflow container

tests/utils/test_shared_process_pool.py
`test_shared_process_pool.py` is taking longer than expected when running on remote-ci, causing multiple ci pipelines failed due to (1h) timeout. 
This is probably because:
- The number of workers of `SharedProcessPool` is set to `0.5 * os.sched_getaffinity(0)` by default. If the test is running on a machine that has 64 cores, it will maintain 32 sub-processes.
- For each unit test, the process pool need to create all the sub-processes and then `join()` all of them when tear down, which might be slow when the number of processes is large.
- Running the test in remote-ci is slower than running locally, probably because there are multiple ci jobs running on the same machine
The test should run faster by setting the number of workers to `0.1 * os.sched_getaffinity(0)` and it should avoid ci …
=> Set lower CPU usage for `test_shared_process_pool.py` to avoid slowing down the test

.github/workflows/ci_pipe.yml, examples/gnn_fraud_detection_pipeline/stages/model.py, examples/llm/common/utils.py, examples/llm/vdb_upload/langchain.py, examples/llm/vdb_upload/module/content_extractor_module.py, examples/llm/vdb_upload/module/file_source_pipe.py, examples/llm/vdb_upload/module/rss_source_pipe.py, examples/llm/vdb_upload/module/schema_transform.py, examples/llm/vdb_upload/module/vdb_resource_tagging_module.py, examples/llm/vdb_upload/module/web_scraper_module.py, pyproject.toml, python/morpheus/morpheus/modules/schemas/deserialize_schema.py, python/morpheus/morpheus/modules/schemas/multi_file_source_schema.py, python/morpheus/morpheus/modules/schemas/rss_source_schema.py, python/morpheus/morpheus/stages/input/arxiv_source.py, python/morpheus/morpheus/stages/input/http_server_source_stage.py, python/morpheus/morpheus/utils/column_info.py, python/morpheus_llm/morpheus_llm/modules/schemas/write_to_vector_db_schema.py, tests/_utils/test_directories.py, tests/conftest.py, tests/examples/gnn_fraud_detection_pipeline/conftest.py, tests/examples/llm/common/conftest.py, tests/examples/ransomware_detection/conftest.py, tests/morpheus/conftest.py, tests/morpheus/stages/test_multi_processing_stage.py, tests/morpheus/utils/test_downloader.py, tests/morpheus_dfp/conftest.py, tests/morpheus_llm/stages/arxiv/conftest.py, tests/morpheus_llm/stages/arxiv/test_arxiv_source.py
* Code updates to avoid several future & deprecation warnings
* Most of these are the result of recent package updates, specifically from `pydantic` and `langchain`
* Mark slow `MultiProcessingStage` tests as slow
* Number of reported warnings produced when running `pytest` from 48 to 10
* Consolidate redundant fixtures
* Increase CI timelimit for tests to 90 minutes
=> Reduce the number of warnings emitted

ci/vale/styles/config/vocabularies/morpheus/accept.txt, docs/CMakeLists.txt, docs/source/conda_packages.md, docs/source/getting_started.md, docs/source/index.rst, docs/source/py_api.rst, docs/source/stages/morpheus_stages.md, python/morpheus_dfp/morpheus_dfp/modules/dfp_deployment.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_inference.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_inference_pipe.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_rolling_window.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_split_users.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_training.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_training_pipe.py
- [] Update example READMEs (if needed)
=> Morpheus docs update post compartmentalization

python/morpheus_llm/morpheus_llm/llm/services/nvfoundation_llm_service.py
This PR reverts the removal of the `**kwargs` argument from the `NVFoundationLLMClient.generate_batch()` and `generate_batch_async()` methods, which introduced a regression.
Closes #1961 
=> Add `**kwargs` back to `NVFoundationLLMClient.generate_batch()` and `generate_batch_async()`

.devcontainer/Dockerfile, .devcontainer/cuda12.5-conda/devcontainer.json
This PR is replacing the `VAULT_HOST` variable with `AWS_ROLE_ARN`. This is required to use the new token service to get AWS credentials.
=> devcontainer: replace `VAULT_HOST` with `AWS_ROLE_ARN`

examples/gnn_fraud_detection_pipeline/run.py, examples/ransomware_detection/run.py
This change was made because of check-style failures when tests were refactored but is causing import failures.
Note: This commit also reverts the style fix and the local imports are mis-sorted. We may need to update the style checker to fix it post release.
=> Revert the relative path change used in examples

examples/llm/agents/README.md, examples/llm/completion/README.md, examples/llm/rag/README.md, examples/llm/vdb_upload/README.md
* Agents: Show an actual runnable command that can be copy/pasted, not just the command usage.
* Completion: Remove blank line in command block
* RAG: Remove section about fetching data, RAG doesn't need any LFS files.
* VDB Upload: Pipeline requires the `examples` dataset not the `datasets` dataset.
* VDB Upload: Document how to run Milvus
Closes #1991
=> Fix minor issues with LLM example documentation

examples/digital_fingerprinting/production/README.md
This is to account for the changes done during DFP refactoring
=> Fix up file paths in the DFP README

examples/abp_nvsmi_detection/README.md, examples/nlp_si_detection/README.md, examples/root_cause_analysis/README.md
* The deserialize stage no longer actually deserializes, but instead chunks incoming `MessageMeta` objects and converts to `ControlMessage`
Closes #2007
=> Fix mis-leading deserialize stage comments

python/morpheus/morpheus/_lib/src/messages/meta.cpp, tests/morpheus/apps/test_sid.py, tests/morpheus/apps/test_sid_kafka.py
Closes https://github.com/nv-morpheus/Morpheus/issues/2002
=> Fix offset calculation when taking a slice of a `SlicedMessageMeta`

python/morpheus/morpheus/_lib/src/messages/meta.cpp, python/morpheus/morpheus/_lib/src/stages/deserialize.cpp, tests/morpheus/pipeline/test_file_in_out.py
* `DeserializeStage` now performs a copy of the rows needed for each batch, ensuring each output `ControlMessage` now has a unique `MessageMeta` and underlying `DataFrame`
* Works-around issue where calling `SlicedMessageMeta::get_mutable_info().checkout_obj()` returns the entire `DataFrame`
* This unfortunately means that `DeserializeStage` will require the GIL.
* Remove unused `make_output_message` method
* Avoid some redundant code in `SlicedMessageMeta` (unrelated but I was in this part of the code).
Closes #2002
- When the PR is ready for review, the …
=> Fix `DeserializeStage` to ensure output messages correctly contain the correct rows for each batch

examples/log_parsing/postprocessing.py, python/morpheus/morpheus/_lib/include/morpheus/objects/table_info.hpp, python/morpheus/morpheus/_lib/include/morpheus/stages/deserialize.hpp, tests/examples/log_parsing/test_postprocessing.py
* Use the index of the incoming DF as the source of the `doc` field not the first column of the sequence_ids
* Fix typeo in docstring for `TableInfo::num_indices` (unrelated)
* Remove declaration for unimplemtned/unused function in `python/morpheus/morpheus/_lib/include/morpheus/stages/deserialize.hpp` (unrelated)
Closes #2029
=> Fix for duplicate row IDs in `log_parsing` output

examples/data/root-cause-validation-data-input.jsonlines, examples/root_cause_analysis/README.md
Closes #2030
This is needed to run root_cause_analysis in the release container.
=> Copy data files needed by root_cause_analysis to examples/data

docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md, docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md, docs/source/extra_info/troubleshooting.md, examples/digital_fingerprinting/production/dfp_integrated_training_batch_pipeline.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_deployment.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_inference_pipe.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_preproc.py, python/morpheus_dfp/morpheus_dfp/modules/dfp_training_pipe.py, python/morpheus_dfp/morpheus_dfp/utils/dfp_arg_parser.py
* Replace `Broadcast` with `Router`
* Remove unneeded filter node from `dfp_preproc` module
* Fix DFP file & class paths in documentation
* Remove python blocks from documentation which didn't offer much to readers
Closes #2034 
=> Update DFP integrated pipeline to use MRC `Router` node

examples/developer_guide/3_simple_cpp_stage/CMakeLists.txt, examples/developer_guide/4_rabbitmq_cpp_stage/CMakeLists.txt, python/morpheus/morpheus/_lib/cmake/libmorpheus.cmake, python/morpheus_llm/morpheus_llm/_lib/cmake/libmorpheus_llm.cmake
* Set CMake policy #`CMP0144` to `NEW` in C++ examples, avoids a deprecation warning
* Set `-lto=auto` to avoid a warning about falling back to serialized compilation.
Related to https://github.com/nv-morpheus/MRC/pull/518 .
Closes #1988
=> Avoid compiler warnings

docker/run_container_dev.sh, docker/run_container_release.sh
* Allow the user to optionally run something other than `bash` when using `docker/run_container_release.sh` and `docker/run_container_dev.sh`
=> Allow running something other than bash when using docker scripts

python/morpheus/morpheus/_lib/cudf_helpers.pyx
In anticipation of this downstream cuDF PR removing some functionality in `cudf._lib.utils` https://github.com/rapidsai/cudf/pull/17586, this PR replaces that usage with equivalent usage from the stable `pylibcudf`
=> Remove cudf._lib.utils usage in favor of pylibcudf

models/triton-model-repo/phishing-bert-onnx/config.pbtxt, models/triton-model-repo/sid-minibert-onnx/config.pbtxt
When running Triton inference for SID & Phishing detection pipeline using multi-gpu on `nvcr.io/nvidia/morpheus/morpheus-tritonserver-models:24.11`. It result on segment fault.  The  TRT optimization line  at the config.pbtxt of the models is causing  `tritonserver:24.11` to fail with following error.  This PR address the issue to run when all gpu is selected for inference.
> 2024-12-09 23:24:38.378753895 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running TRTKernel_graph_torch_jit_3139280210422962738_0 node. Name:'TensorrtExecutionProvider_TRTKernel_graph_torch_jit_3139280210422962738_0_0' Status Message: TensorRT EP execution context enqueue failed.
Closes #2028 
- I am familiar with the [Contributing …
=> Remove triton optimization config, causing error for multi gpu inference

.devcontainer/Dockerfile, docker/Dockerfile, examples/digital_fingerprinting/production/Dockerfile, examples/digital_fingerprinting/production/docker-compose.yml, examples/sid_visualization/docker-compose.yml
* According to https://docs.docker.com/compose/how-tos/gpu-support/ "If count is set to all or not specified, all GPUs available on the host are used by default." However we have observed the opposite, that by not specifying count the container doesn't have access to any GPUs.
* Update `Dockerfile`s to ensure the `FROM x AS y` lines have consistent casing, avoids a build warning in newer versions of Docker.
Closes #2099
Closes #2102
=> Specify `count: all` for GPU resources in docker compose yamls

ci/release/update-version.sh, dependencies.yaml, docs/source/developer_guide/guides/5_digital_fingerprinting.md, examples/digital_fingerprinting/fetch_example_data.py, examples/digital_fingerprinting/production/Dockerfile, examples/digital_fingerprinting/production/README.md, examples/digital_fingerprinting/production/conda/environments/dfp_example_cuda-125_arch-x86_64.yaml, examples/digital_fingerprinting/production/dfp_azure_pipeline.py, examples/digital_fingerprinting/production/dfp_duo_pipeline.py, examples/digital_fingerprinting/production/dfp_integrated_training_batch_pipeline.py, examples/digital_fingerprinting/production/dfp_integrated_training_streaming_pipeline.py, examples/digital_fingerprinting/production/docker-compose.yml, examples/digital_fingerprinting/production/grafana/run.py, python/morpheus/morpheus/stages/general/monitor_stage.py
* Only build a C++ node for `MonitorStage` if the message type is supported on the C++ side.
* Ensure the `MonitorStage` is omitted from the pipeline if silenced by the configured log level (this optimization existed for the Python node, this change just applies it to the C++ node).
* Update the version of Morpheus used by the DFP Docker containers, and add it to the `ci/release/update-version.sh` script.
* Set the default log level for DFP pipelines to `INFO`
* Document fetching the DFP datasets from within the docker container. This allows for an all-docker workflow, and avoids the need for users to create a Conda environment on their host system just to download the example data.
* Document that the DFP pipelines can be run from either the CLI or from a Jupyter Notebook.
* Update …
=> Improved DFP documentation, logging and fix MonitorStage

ci/conda/recipes/morpheus-libs/meta.yaml, ci/conda/recipes/morpheus/meta.yaml, docker/Dockerfile
* `indicators` was added as a dependency but hasn't been added to the Conda meta.yaml files.
* Mount the pip cache dir as a shared cache, this prevents the pip cache from being published in the container, reducing the image size by 3GB!
=> Add missing indicators lib to conda package

python/morpheus/morpheus/_lib/cudf_helpers.pyx
Related to https://github.com/rapidsai/cudf/issues/17317, `cudf._lib.column.Column` is being phased out in favor of using pylibcudf.
I found some locations where `cudf._lib.column.Column` was used as type annotations in Cython; however, the accessed or returned objects were calling Python defined attributes/methods or used as objects in other Python objects respectively. Therefore, I don't suspect the annotations are entirely performance critical here
=> Remove some cudf._lib.column.Column annotations in Cython

python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp
* Fixes issue where a pipeline completes, and the shell prompt appears in the middle of the pipeline output, overwriting some of the output, and making it difficult to even notice the pipeline completed.
* Add new `mark_pbar_as_completed` method to `ProgressBarContextManager`, which will return the cursor to the bottom of the output.
* `MonitorController` no longer calls `mark_as_completed` on `ProgressBar` objects, instead uses `ProgressBarContextManager::mark_pbar_as_completed`.
Closes #2119
- When the PR is ready for review, the documentation is up to date with …
=> Ensure `MonitorStage` returns the cursor back to the end of output

CMakeLists.txt, ci/scripts/github/cmake_all.sh, cmake/package_search/Finddoca.cmake, cmake/package_search/Findlibdpdk.cmake
* Remove hard-coded `x86_64` values in CMake scripts for DOCA 
* Define `CMAKE_LIBRARY_ARCHITECTURE` in top-level `CMakeLists.txt` as this controls which directories are searched by `find_library` (https://cmake.org/cmake/help/v2.8.8/cmake.html#command:find_library).
Closes #2092
=> Fix DOCA builds on ARM64

examples/abp_pcap_detection/abp_pcap_preprocessing.py
* Avoid redundant calls to `get_data`
* Avoid pandas conversion when converting the `flags` field to a binary number.
=> Performance improvements for `AbpPcapPreprocessingStage`

examples/developer_guide/2_2_rabbitmq/README.md, examples/developer_guide/4_rabbitmq_cpp_stage/README.md, python/morpheus/morpheus/stages/postprocess/generate_viz_frames_stage.py
* Don't log error messages if `_server_close_event` has already been set.
* Unrelated documentation improvement for the RabbitMQ examples to ensue the `MORPHEUS_ROOT` environment variable is set.
Closes #2135
=> Suppress spurious socket error messages from `GenerateVizFramesStage`  on shutdown

examples/abp_nvsmi_detection/README.md
- Update reference to output file to match name used in command
- Change `0` and `1` to `false` and `true` in example results to match what was seen after running example
=> Update `abp_nvsmi_detection` example README

python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp
- [#2121](https://github.com/nv-morpheus/Morpheus/pull/2121) ensures the cursor is reset to the last line of output after shutdown by adding `ProgressBarContextManager::mark_pbar_as_completed()`. 
- When executing some of the pipelines, race conditions may cause calling `ProgressBarContextManager::display_all()` after `ProgressBarContextManager::mark_pbar_as_completed()`, which intermittently causes the log display issue above - which should has been fixed by this PR.
Closes #2119 
=> Fix C++ version of `MonitorStage` output issue caused by out of order function calls

examples/gnn_fraud_detection_pipeline/README.md
* Set the output directory to `.tmp/output` to match other examples.
=> Fix output directory for `gnn_fraud_detection_pipeline` example

examples/log_parsing/README.md, examples/log_parsing/postprocessing.py
* Fix file paths for CLI example to not use the models dir, as this directory doesn't exist in the release container
* Use the MorpheusRelativePath to resolve the vocab_path and model_config_path CLI arguments
Closes #2144
=> Fix file paths in `log_parsing` CLI example

examples/developer_guide/3_simple_cpp_stage/CMakeLists.txt, examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/CMakeLists.txt, examples/developer_guide/4_rabbitmq_cpp_stage/CMakeLists.txt, examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/_lib/CMakeLists.txt
* Explicitly call `find_package(glog REQUIRED)` and link to `glog::glog` in C++ examples
* This is a work-around for issue #2149
=> Work-around glog dependency issues for C++ examples

docs/source/extra_info/known_issues.md, docs/source/getting_started.md, examples/digital_fingerprinting/production/Dockerfile, examples/digital_fingerprinting/production/grafana/README.md
* Document Arm64 performance issues on older Linux Kernels
* Manually install PyTorch in the DFP container allowing Arm64 users to run the pipeline work-around issue #2095 (fix slated for PyTorch 2.6 / Morpheus 25.06).
Closes #2120
Closes #2124
=> Document known Arm64 issues and work-around PyTorch installation issues for DFP

python/morpheus/morpheus/_lib/common/__init__.pyi, python/morpheus/morpheus/_lib/common/module.cpp, python/morpheus/morpheus/_lib/include/morpheus/utilities/cudf_util.hpp, python/morpheus/morpheus/_lib/src/io/deserializers.cpp, python/morpheus/morpheus/_lib/src/io/serializers.cpp, python/morpheus/morpheus/_lib/src/utilities/cudf_util.cpp, python/morpheus/morpheus/_lib/tests/test_utils/common.cpp, python/morpheus/morpheus/common/__init__.py, python/morpheus/morpheus/pipeline/pipeline.py, python/morpheus/morpheus/stages/input/kafka_source_stage.py
* Calling  `CudfHelper::load()` from a MRC thread that Python didn't know about was cuassing the deadlock in issue #2204
* The issue appears to be that `CudfHelper::load()` called `import_morpheus___lib__cudf_helpers` which in turn called `PyImport_ImportModule` which would abort the running thread, even though the thread was holding the GIL.
Closes #2204
=> Invoke `CudfHelper::load()` from the main Python thread

ci/conda/recipes/morpheus-libs/meta.yaml, ci/conda/recipes/morpheus/meta.yaml, ci/scripts/run_ci_local.sh, conda/environments/all_cuda-128_arch-aarch64.yaml, conda/environments/all_cuda-128_arch-x86_64.yaml, conda/environments/dev_cuda-128_arch-aarch64.yaml, conda/environments/dev_cuda-128_arch-x86_64.yaml, conda/environments/examples_cuda-128_arch-aarch64.yaml, conda/environments/examples_cuda-128_arch-x86_64.yaml, conda/environments/runtime_cuda-128_arch-aarch64.yaml, conda/environments/runtime_cuda-128_arch-x86_64.yaml, dependencies.yaml, tests/conftest.py, tests/morpheus/test_cli.py
* Looks like I forgot to update this dep the conda recipe in PR #2203
* Remove pin for mlflow and fix tests, thanks to suggestion from @willkill07 
* Fix out of date container image in `ci/scripts/run_ci_local.sh` script
* Pin setuptools to a range of `>=75,<80` to work-around deprecated functionality which was removed in v80 (#2224).
* Ensure cudf helper is loaded prior to running tests
Closes #2066
Closes #2228
=> Fix conda package dependency issues

conda/environments/all_cuda-128_arch-x86_64.yaml, conda/environments/dev_cuda-128_arch-x86_64.yaml, conda/environments/examples_cuda-128_arch-x86_64.yaml, conda/environments/runtime_cuda-128_arch-x86_64.yaml, dependencies.yaml, python/morpheus_llm/morpheus_llm/requirements_morpheus_llm_arch-aarch64.txt, python/morpheus_llm/morpheus_llm/requirements_morpheus_llm_arch-x86_64.txt
The dataclasses package currently clamps <4 but that package doesn't appear in the dev env, only in the all env.
Closes #2232
=> Clamp marshmallow to <4 to avoid version incompatibilities

examples/digital_fingerprinting/production/Dockerfile
Fixes the DFP example not building due to the Dockerfile referencing an outdated Conda environment file.
Updated the environment file reference from `dfp_example_cuda-125_arch-$(arch).yaml` to `dfp_example_cuda-128_arch-$(arch).yaml` to match the currently available config.
=> Fix script reference in DFP example's Dockerfile from 125 to 128

python/morpheus/morpheus/_lib/src/objects/table_info.cpp
* Fixes an issue where a filter stage ends up dropping all rows in an instance of `SlicedMessageMeta`
* Add an exception to one of the pre-flight asserts in table_info.cpp
Closes #2239
=> Allow empty DataFrame slices

examples/data_loss_prevention/dlp_stages/_lib/CMakeLists.txt, examples/developer_guide/3_simple_cpp_stage/compile.sh, examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/CMakeLists.txt, examples/developer_guide/4_rabbitmq_cpp_stage/compile.sh, examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/_lib/CMakeLists.txt
There was a linker error on aarch64 indicating that `-lmorpheus` could not be found.
Two possible solutions existed:
1. change the LINK_TARGETS from `morpheus` to `morpheus::morpheus`
2. add `find_library` calls to find the morpheus shared library on the system.
(1) unfortunately resulted in a public link failing of mrc::pymrc -- which probably indicates that we shouldn't be exposing that as a public link dependency.
(2) was chosen because it's what we'd expect the system to do -- find the installed morpheus shared object file and link to it.
It's a bit cumbersome but it works as intended. This is more of a hotfix/patch rather than a complete engineered solution. Improvements and enhancements are welcome.
Closes 
- I am familiar with the [Contributing …
=> Fix: examples build on aarch64

.devcontainer/Dockerfile, .devcontainer/cuda12.8-conda/devcontainer.json, .devcontainer/unset-safepath.sh, docs/source/extra_info/known_issues.md, examples/data_loss_prevention/README.md, examples/log_parsing/README.md
* Ensure that the `PYTHONSAFEPATH` environment variable is not set inside the devcontainer.
* Disable DOCA builds inside the devcontainer, work-around for #2285 
* Fix triton server urls for devcontainer examples
* Document known 25.06 issues
Closes #2286
=> Fix devcontainer builds

examples/data_loss_prevention/dlp_stages/_lib/CMakeLists.txt, examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/CMakeLists.txt, examples/developer_guide/4_rabbitmq_cpp_stage/src/rabbitmq_cpp_stage/_lib/CMakeLists.txt
This PR fixes a typo in the CMake variable name `PROJECT_IS_TOP_LEVEL` so we can properly detect how to link Morpheus when building the examples as part of Morpheus or separately.
Closes #2276
=> Fix: typo for PROJECT_IS_TOP_LEVEL for building examples
