- docker/build_container.sh
> Minor update for clarity

- morpheus/pipeline/output/to_file.py
> fix to_file "overwrite" option for cli

- morpheus/cli.py
> Removing `no_args_is_help` from CLI commands

- docs/source/conf.py
- morpheus/cli.py
- morpheus/utils/onnx_to_trt.py
> TensorRT installation warning for onnx_to_trt

- docs/source/morpheus_quickstart_guide.md
Fix to broken morpheus developer guide link.
> Quickstart guide changes

- CONTRIBUTING.md
Use github pull-request terminology instead of gitlab merge-request.
Add clarity to finding the first issue sentence
Remove unnecessary line breaks
> CONTRIBUTING.md typeos

- examples/abp_nvsmi_detection/README.md
> Update abp_nvsmi_detection example

- examples/log_parsing/README.md
> Update license header for readme

- morpheus/pipeline/output/to_file.py
- tests/conftest.py
- tests/test_file_in_out_stage_pipe.py
> Fixes bug in WriteToFileStage when configured with a filename without a path

- docker/conda/environments/cuda11.4_dev.yml
> Add pybind11-stubgen to conda environment yaml.

- docker/Dockerfile
> Add missing git-lfs package to docker container

- CMakeLists.txt
- ci/Jenkinsfile
Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

- morpheus/cli.py
- morpheus/pipeline/pipeline.py
- tests/test_pipe_viz.py
Adds a busy-loop to block until pipeline build is completed.
Fixes #188
Ideally https://github.com/nv-morpheus/SRF/issues/68 would provide a better way to do this.
> Fixes Pipeline.visualize 

- examples/ransomware_detection/common/data_models.py
- examples/ransomware_detection/common/feature_extractor.py
- examples/ransomware_detection/stages/create_features.py
Reverted ransomware feature config changes as dask is overriding config values.
> Revert ransomware feature config changes

- examples/gnn_fraud_detection_pipeline/README.md
`chardet` package now required by stellargraph
Also, switching to mamba for speed and conda seemed to struggle solving env.
Not sure if we should start pinning these?
> Update GNN example readme

- docs/source/morpheus_quickstart_guide.md
`./morpheus/data/' -> `data/` wherever we load vocab files, etc.
Fixes #301
> QSG updates for data dir

- docs/source/morpheus_quickstart_guide.md
Relates to nv-morpheus/SRF#157
> Add Azure known issue to QSG

- docs/source/morpheus_quickstart_guide.md
> Clarification of known issue in QSG

- examples/README.md
> Initial example readme

- .gitmodules
- ci/scripts/jenkins/test.sh
- docker/Dockerfile
Fixes #363 
Feels a little weird to leave in so much .git in the image, not just the submodule. Might be worth further discussion.
> Adjustments for docker build inclusion of morpheus-visualization

- docker/conda/environments/cuda11.5_dev.yml
> Pin numba version

- morpheus/cli/commands.py
> Set a default value for --columns_file and populate the help string

- CHANGELOG.md
- examples/log_parsing/preprocessing.py
- morpheus/_lib/include/morpheus/stages/preprocess_nlp.hpp
- morpheus/_lib/src/python_modules/stages.cpp
- morpheus/_lib/src/stages/preprocess_nlp.cpp
- morpheus/stages/preprocess/preprocess_nlp_stage.py
- morpheus/utils/logger.py
- tests/conftest.py
- tests/test_sid.py
This is the PR containing all of the changes for the 22.06.01 Hotfix
> [RELEASE] Morpheus v22.09.01 Hotfix

- models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.py
- models/training-tuning-scripts/abp-models/requirements.txt
in the example python statement, there was an extra hyphen, and autogenerated req was missing libraries, and adding sklearn
Closes #454
> ABP change the arg name in the comment and update req 

- docs/source/developer_guide/guides/2_real_world_phishing.md
work-around for #475 & https://github.com/triton-inference-server/server/issues/5084
> Use tritonserver 22.06 for the phishing example

- ci/conda/recipes/morpheus/meta.yaml
- docker/Dockerfile
- docker/conda/environments/cuda11.5_dev.yml
- docker/conda/environments/cuda11.5_runtime.yml
- docker/conda/environments/requirements.txt
- examples/digital_fingerprinting/production/README.md
- examples/digital_fingerprinting/production/mlflow/Dockerfile
- models/mlflow/docker/Dockerfile
- models/mlflow/docker/conda/mlflow-env.yml
Forward-merge triggered by push to `branch-22.11` that creates a PR to keep `branch-23.01` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.11 to branch-23.01 [skip gpuci]

- docs/README.md
- docs/source/cloud_deployment_guide.md
> Update cloud deployment guide and fix doc build instructions.

- docs/source/index.rst
> Remove search link from index.rst

- examples/digital_fingerprinting/production/conda_env.yml
- examples/digital_fingerprinting/production/docker-compose.yml
> Update container version to 23.01 in DFP docker-compose

- examples/abp_pcap_detection/run.py
- examples/gnn_fraud_detection_pipeline/run.py
- examples/log_parsing/run.py
- examples/ransomware_detection/run.py
- examples/sid_visualization/run.py
- morpheus/stages/postprocess/serialize_stage.py
- morpheus/stages/preprocess/deserialize_stage.py
- Updated `run.py` file outdated comments for all the examples.
> Removed outdated comments

- docs/source/cloud_deployment_guide.md
- docs/source/developer_guide/guides/5_digital_fingerprinting.md
- examples/digital_fingerprinting/production/README.md
Fix script paths in example production Azure/Duo DFP pipeline run commands.
> Fix production DFP pipeline run commands

- .gitmodules
Update `morpheus-visualizations` submodule to `branch-23.01`.
> Update morpheus-visualizations submodule

- pyproject.toml
Added testpaths to `pyproject.toml`
> Add Pytest 'testpaths'

- morpheus.code-workspace
- morpheus/cli/commands.py
- morpheus/cli/register_stage.py
- morpheus/cli/utils.py
- morpheus/stages/input/file_source_stage.py
- morpheus/stages/input/kafka_source_stage.py
- morpheus/stages/output/write_to_file_stage.py
- morpheus/stages/postprocess/filter_detections_stage.py
- tests/test_cli.py
Forward-merge triggered by push to `branch-23.01` that creates a PR to keep `branch-23.03` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.01 to branch-23.03

- morpheus/_lib/tests/CMakeLists.txt
- morpheus/_lib/tests/test_morpheus.cpp
- morpheus/_lib/tests/test_morpheus.hpp
* Allows testing parts of the C++ code that interact with Python
* Devin's code from issue #595 
* Pulling this out into its own PR since I needed similar
> New base test class that invokes an embedded Python interpreter

- docs/source/conf.py
Fixes source links from docs 
fixes #773
> Fix source code links from docs

- examples/digital_fingerprinting/starter/run_cloudtrail_dfp.py
> Change userid_column_name to match the command line equivelants

- examples/log_parsing/messages.py
- examples/log_parsing/preprocessing.py
- examples/ransomware_detection/stages/preprocessing.py
Both examples were broken by recent changes to the message classes
fixes #791 
fixes #796
- [-] New or existing tests cover these changes.
> Fix for log_parsing and ransomware_detection examples

- morpheus/stages/postprocess/timeseries_stage.py
- morpheus/stages/preprocess/preprocess_ae_stage.py
Forward-merge triggered by push to `branch-23.03` that creates a PR to keep `branch-23.07` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.03 to branch-23.07

- docs/source/developer_guide/contributing.md
Fix contributing.md - adding a step to fetch data sets before running pytest.
> fix_contrib_instructions

- examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_viz_postproc.py
- Change input type in `DFPVizPostprocStage` to `MultiAEMessage` to match output type of `DFPInferenceStage`.
- Update `morpheus-visualizations` submodule to latest commit.
Fixes #1042
> DFP visualization updates/fixes

- docs/source/developer_guide/guides/5_digital_fingerprinting.md
- examples/digital_fingerprinting/production/README.md
fixes https://github.com/nv-morpheus/Morpheus/issues/919
> Add note about needing docker-compose v1.28+ for DFP

- models/triton-model-repo/phishing-bert-onnx/config.pbtxt
- tests/benchmarks/conftest.py
Forward-merge triggered by push to `branch-23.07` that creates a PR to keep `branch-23.11` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.07 to branch-23.11

- CHANGELOG.md
This is the PR containing all of the changes for the 23.07.01 Hotfix
> [RELEASE] Morpheus v23.07.01 Hotfix

- CHANGELOG.md
Fixes the forward merger conflicts in PR #1091
> Resolve forward merger conflices for `branch-23.11`

- tests/benchmarks/e2e_test_configs.json
* Update feature length to match value used in tests/test_abp.py
fixes #1187 
> Update feature length  for test_abp_fil_e2e benchmark

- examples/abp_pcap_detection/README.md
+ Add more detail to Triton server setup instructions
Closes #1201
> ABP PCAP detection readme update

- docker/conda/environments/cuda11.8_dev.yml
* Set nodejs version to 18.*
Closes #1259
> Loosen nodejs version restriction

- examples/digital_fingerprinting/production/docker-compose.yml
This fixes the merge conflicts reported by the auto merger in #1258
> Resolve merge conflicts between 23.07 and 23.11

- morpheus/_lib/tests/llm/test_llm_node.cpp
- morpheus/_lib/tests/llm/test_utils.cpp
* A few odds and ends I added poking around the LLM tests
> Minor additions to llm tests

- docker/conda/environments/cuda11.8_dev.yml
- morpheus/llm/services/llm_service.py
- tests/llm/services/test_llm_service.py
* Add docstring
* Add nominal test, but since these are both interfaces there wasn't much to actually test
Closes #1303
> Docstrings for LLMService & LLMClient

- morpheus/llm/nodes/langchain_agent_node.py
- tests/llm/nodes/conftest.py
- tests/llm/nodes/test_langchain_agent_node.py
- tests/llm/nodes/test_langchain_agent_node_pipe.py
* Add docstrings for `LangChainAgentNode`
* Add tests for `LangChainAgentNode`
Closes #1299
> Docstrings and tests for LangChainAgentNode

- examples/llm/common/web_scraper_stage.py
- tests/examples/llm/common/conftest.py
- tests/examples/llm/common/test_web_scraper_stage.py
- tests/mock_rest_server/mocks/www/index/GET.mock
Closes https://github.com/nv-morpheus/Morpheus/issues/1283
> Add docs and tests for WebScraperStage

- morpheus/cli/commands.py
> Register DataBricksDeltaLakeSourceStage with the CLI

- tests/test_milvus_vector_db_service.py
> Add missing milvus marker

- docs/source/extra_info/troubleshooting.md
* Adds entry to `docs/source/extra_info/troubleshooting.md` regarding incompatible MLflow models.
Closes #1409
> Document incompatible mlflow models issue

- morpheus.code-workspace
Removes the deprecated python settings in favor of the options recommended in https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions
> Updating the workspace settings to remove deprecated python options

- docs/source/getting_started.md
This PR updates the link to Basic Usage to point to the correct file.
> Fix broken link in getting started with Morpheus doc

- morpheus/_lib/llm/include/py_llm_engine_stage.hpp
> Update to match new MRC function sig for AsyncioRunnable::on_data

- conda/environments/all_cuda-121_arch-x86_64.yaml
- conda/environments/dev_cuda-121_arch-x86_64.yaml
- conda/environments/examples_cuda-121_arch-x86_64.yaml
- conda/environments/runtime_cuda-121_arch-x86_64.yaml
- dependencies.yaml
Adding missing dependency on pydantic
> Adding missing dependency on `pydantic`

- examples/cyber_dev_day/notebooks/cyber-dev-day.ipynb
Fix the examples in section 1.4
> Fix section 1.4

- CHANGELOG.md
- ci/conda/recipes/morpheus/meta.yaml
- ci/scripts/download_kafka.py
- conda/environments/all_cuda-121_arch-x86_64.yaml
- conda/environments/dev_cuda-121_arch-x86_64.yaml
- conda/environments/examples_cuda-121_arch-x86_64.yaml
- conda/environments/runtime_cuda-121_arch-x86_64.yaml
- dependencies.yaml
- examples/digital_fingerprinting/production/conda_env.yml
- examples/digital_fingerprinting/production/mlflow/Dockerfile
- models/mlflow/README.md
- models/mlflow/docker/Dockerfile
* Manually resolving conflicts from #1614
> Forward-merge branch-24.03 into branch-24.06

- docs/source/extra_info/known_issues.md
> Document current known issues in 24.03.02

- examples/developer_guide/4_rabbitmq_cpp_stage/README.md
> Fix type-o in documentation

- examples/llm/agents/README.md
> Fix mis-spelling of examples

- morpheus/llm/services/llm_service.py
- morpheus/utils/logger.py
- tests/benchmarks/conftest.py
- tests/conftest.py
- tests/llm/services/test_llm_service.py
- tests/llm/services/test_openai_chat_service.py
- tests/test_cli.py
- tests/test_dfp_kafka.py
- tests/test_logger.py
- tests/tests_data/logging.json
* Allows for classes to be replaced by mocks and factory methods
* Improved error message for missing service
* Fix broken tests
* Add new tests
> Replace `isinstance` check with with `callable` in `LLMService.create`

- conda/environments/examples_cuda-121_arch-x86_64.yaml
- dependencies.yaml
- docker/Dockerfile
* Add `python-docx` to the examples conda env, this package is used by `examples/llm/vdb_upload/module/content_extractor_module.py`
* Ensure the `/opt/conda/conda-bld` dir exists
> Release container fixes

- docs/source/extra_info/known_issues.md
- examples/llm/agents/README.md
* Fix urls for other known issues
> Mark the LLM Agents Kafka pipeline as broken

- docs/source/examples/llm/index.rst
- examples/doca/README.md
- examples/llm/agents/README.md
- examples/llm/completion/README.md
* This fixes the way the documents appear in the TOC
> Cleanup docs so that each as a single H1 title

- examples/digital_fingerprinting/production/docker-compose.yml
- examples/sid_visualization/docker-compose.yml
* Avoids warning when executing `docker compose` commands
Closes #1771
> Remove obsolete version string from compose yamls

- morpheus.code-workspace
This is a fixup to commit 4e3edb9653e4f that refactored the setup files
Closes 
> Update location of morpheus setup and data files in VS settings

- ci/scripts/fix_all.sh
Update `isort` settings file path in `fix_all.sh` to `${PROJ_TOML}` so that this script finds the config path correctly. 
This is a follow-up PR of #1854.
> Update `isort` settings file path in `fix_all.sh` 

- ci/scripts/download_kafka.py
Fixes Kafka download script to use an available Kafka version.
> Update Kafka DL script to `2.13-3.8.0`

- .github/workflows/pr.yaml
- CHANGELOG.md
- conda/environments/all_cuda-121_arch-x86_64.yaml
- conda/environments/dev_cuda-121_arch-x86_64.yaml
- conda/environments/examples_cuda-121_arch-x86_64.yaml
- dependencies.yaml
- examples/llm/vdb_upload/module/content_extractor_module.py
Only critical/hotfix level issues should be merged into `branch-24.06` until release (merging of this PR).
All other development PRs should be retargeted towards the next release branch: `branch-24.10`.
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-24.06` into `main` for the release
> [RELEASE] Morpheus v24.06.01

- .pre-commit-config.yaml
- pyproject.toml
> Run pre-commit on all files, not just python

- .github/workflows/pr.yaml
* Fixes a CI error that popped up this morning
> Fix `Can't find 'action.yml'` CI error

- python/morpheus_llm/morpheus_llm/llm/services/nemo_llm_service.py
- python/morpheus_llm/morpheus_llm/llm/services/openai_chat_service.py
* Should be the example not the dev yaml
> Fix conda path for missing llm packages

- CMakeLists.txt
Changed the MORPHEUS_BUILD_MORPHEUS_LLM default to ON
> Build morpheus_llm by default

- python/morpheus/morpheus/stages/input/http_server_source_stage.py
Closes [#1919](https://github.com/nv-morpheus/Morpheus/issues/1919)
> Remove debug log in `HttpServerSourceStage` when the queue is empty

- scripts/morpheus_namespace_update.py
- tests/conftest.py
- tests/scripts/conftest.py
- tests/scripts/data/dfp_old_namespace_data.py
- tests/scripts/data/llm_old_namespace_data.py
- tests/scripts/test_namespace_update.py
Usage:
```
pytest tests/scripts/
```
> Unit tests for the namespace update script

- python/morpheus/morpheus/_lib/src/modules/data_loader_module.cpp
Depends on PR https://github.com/nv-morpheus/MRC/pull/511 being completed, merged, and a new conda package uploaded before testing can begin.
Fixes a small issue where MRC updated a function to be private to avoid incorrect usage of it.
> Update Utilities submodule and fix compilation with latest build of MRC

- docs/source/conda_packages.md
> Incorporate review comments in the conda packages documentation

- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/environments/examples_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- examples/digital_fingerprinting/production/conda/environments/dfp_example_cuda-125_arch-x86_64.yaml
> Pin boto3 and s3fs to compatible versions to resolve access denied errors

- ci/iwyu/mappings.imp
- examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/_lib/pass_thru.hpp
- python/morpheus/morpheus/_lib/include/morpheus/objects/memory_descriptor.hpp
- python/morpheus/morpheus/_lib/include/morpheus/utilities/json_types.hpp
- python/morpheus/morpheus/_lib/include/morpheus/utilities/stage_util.hpp
- python/morpheus/morpheus/_lib/src/io/deserializers.cpp
- python/morpheus/morpheus/_lib/src/objects/dtype.cpp
- python/morpheus/morpheus/_lib/src/objects/mutable_table_ctx_mgr.cpp
- python/morpheus/morpheus/_lib/src/objects/rmm_tensor.cpp
- python/morpheus/morpheus/_lib/src/objects/tensor.cpp
- python/morpheus/morpheus/_lib/src/utilities/table_util.cpp
- python/morpheus/morpheus/_lib/tests/messages/test_message_meta.cpp
- python/morpheus/morpheus/_lib/tests/test_deserializers.cpp
- python/morpheus/morpheus/_lib/tests/test_dev_mem_info.cpp
- python/morpheus_llm/morpheus_llm/_lib/src/llm/llm_engine.cpp
- python/morpheus_llm/morpheus_llm/_lib/src/llm/llm_node_runner.cpp
- python/morpheus_llm/morpheus_llm/_lib/tests/llm/test_llm_task_handler_runner.cpp
- tests/_utils/__init__.py
- tests/scripts/data/dfp_old_namespace_data.py
- tests/scripts/data/llm_old_namespace_data.py
> Various Lint fixes

- docs/source/developer_guide/guides/10_modular_pipeline_digital_fingerprinting.md
- docs/source/developer_guide/guides/6_digital_fingerprinting_reference.md
- docs/source/extra_info/troubleshooting.md
* Update to reflect changes due to the `morpheus_dfp` refactor.
Closes #2051
> Update DFP class and file paths

- ci/release/update-version.sh
- docker/Dockerfile
- thirdparty/README.md
* Needed for open source requirements
> Document location of third party source repository

- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/environments/dev_cuda-125_arch-x86_64.yaml
- conda/environments/examples_cuda-125_arch-x86_64.yaml
- conda/environments/runtime_cuda-125_arch-x86_64.yaml
- dependencies.yaml
Changes from https://github.com/mlflow/mlflow/commit/55418887caf1ef72e3011aa570d9b6e4ce5ecdba#diff-b33420360cc29a5224c8d3080bbfcaa0ac1c8891416137e13be044fcdfdd26f9R92
Closes 
> Pin mlflow version to avoid breaking changes in v2.18

- ci/release/update-version.sh
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/environments/dev_cuda-125_arch-x86_64.yaml
- conda/environments/examples_cuda-125_arch-x86_64.yaml
- conda/environments/runtime_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- docker/Dockerfile
- thirdparty/README.md
Manually resolving conflicts from forwar-merger PR #2060
> Forward-merge branch-24.10 into branch-25.02

- .github/workflows/pr.yaml
- ci/conda/recipes/morpheus-libs/meta.yaml
- ci/conda/recipes/morpheus/meta.yaml
* This would enable conda package uploads for releases, matching the behavior in MRC
Closes https://github.com/nv-morpheus/Morpheus/issues/2042
> Execute CI on the main branch

- ci/conda/recipes/morpheus-libs/meta.yaml
- ci/conda/recipes/morpheus/meta.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/environments/examples_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- docker/Dockerfile
- examples/llm/agents/common.py
- python/morpheus_llm/morpheus_llm/requirements_morpheus_llm.txt
- tests/_utils/llm.py
- tests/morpheus_llm/llm/nodes/test_langchain_agent_node.py
- tests/morpheus_llm/llm/test_agents_simple_pipe.py
* Work-around known openai incompatibility with httpx v0.28 (openai/openai-python#1915)
* Templatize the llm pip dependencies
* Replace deprecated imports of openai from langchain and langchain_community 
Closes #2084 
> Fix openai validation error

- examples/ransomware_detection/README.md
> Update `ransomware_detection` documentation to reflect default Dask values

- .devcontainer/bin/dev-kafka-start
- examples/llm/agents/README.md
> Mention using `--bootstrap_servers` option when running Kafka pipelines in `devcontainer`

- .github/workflows/ci_pipe.yml
* Replace V100 runner with an L4 runner
> CI: Add new L4 runner for test

- .github/workflows/ci_pipe.yml
- ci/conda/recipes/morpheus-libs/meta.yaml
- ci/conda/recipes/morpheus/meta.yaml
- conda/environments/all_cuda-125_arch-aarch64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/environments/dev_cuda-125_arch-aarch64.yaml
- conda/environments/dev_cuda-125_arch-x86_64.yaml
- conda/environments/examples_cuda-125_arch-aarch64.yaml
- conda/environments/examples_cuda-125_arch-x86_64.yaml
- conda/environments/runtime_cuda-125_arch-aarch64.yaml
- conda/environments/runtime_cuda-125_arch-x86_64.yaml
- dependencies.yaml
*  Include back-patch of #2145
Closes #2166
> Pin numba to 0.60

- ci/release/download_deps.py
- models/docker/Dockerfile
- models/docker/build_container.sh
* Perform an `apt update` and `apt upgrade` during the Docker build picking up any security fixes available.
* Add `urllib3` to `ci/release/download_deps.py` (unrelated fix)
> Perform `apt upgrade` during docker build of the models container

- docs/source/developer_guide/guides/2_real_world_phishing.md
* Update the `external/morpheus-visualizations` submodule to adopt fixes from nv-morpheus/morpheus-visualizations#50
> Pick up changes from nv-morpheus/morpheus-visualizations#50

- CHANGELOG.md
Forward merge branch-25.02 into branch-25.06
> Forward merge branch-25.02 into branch-25.06

- docs/source/conf.py
* Add version number to the title
* Add Adobe Analytics to documentation builds
Closes #2141
> Add analytics to rendered documentation

- tests/morpheus/pipeline/test_pipeline_error.py
* Actual bug fix was in nv-morpheus/MRC#547
* This just adds an extra test to ensure the expected outcome on the Morpheus side.
Closes #2202
> Add test to verify that #2202 is fixed

- ci/conda/recipes/python-dbg/conda_build_config.yaml
- docker/Dockerfile
> Fix docker container for Python 3.12

- examples/data_loss_prevention/README.md
Quick PR to format the diagram in the DLP example's README.
> DLP diagram formatting update

- .github/workflows/ci_pipe.yml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/environments/dev_cuda-125_arch-x86_64.yaml
- conda/environments/examples_cuda-125_arch-x86_64.yaml
- conda/environments/runtime_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- docs/source/developer_guide/guides/2_real_world_phishing.md
* Manually resolving conflicts from  #2223
> Forward-merge branch-24.06 into branch-24.10 

- conda/environments/all_cuda-128_arch-aarch64.yaml
- conda/environments/all_cuda-128_arch-x86_64.yaml
- dependencies.yaml
> Add optional databricks packages to the all env, and rename the group

- examples/README.md
Add  DLP pipeline examples in the README.md  content list. 
Closes 
> Update examples content list README.md to include DLP pipeline in the list

- examples/ransomware_detection/run.py
* Offers improved performance on some systems, notably arm systems
> Set a reasonable num_threads default value for ransomware_detection example

- examples/llm/common/utils.py
- examples/llm/completion/README.md
- examples/llm/rag/README.md
- examples/llm/rag/run.py
- examples/llm/rag/standalone_pipeline.py
* Replace the RAG model, resolves issue where the previous model was timing out with connection errors.
* Update documentation to reflect the removal of NeMoLLM (missed in previous PR)
Closes #2281
> Replace default model in RAG pipeline with Nvidia hosted model

- docs/source/developer_guide/guides/3_simple_cpp_stage.md
- examples/developer_guide/3_simple_cpp_stage/src/simple_cpp_stage/pass_thru.py
> Fix type checking of the input message in PassThruStage example

- examples/nlp_si_detection/README.md
> Update nlp_si_detection example `README.md` to reflect that boolean values are used in the output

- examples/data_loss_prevention/README.md
> Document the licences of additional dependencies
